package simpleidp

// Reference material:
// OAuth 2.1 draft 15: https://www.ietf.org/archive/id/draft-ietf-oauth-v2-1-15.txt

import "testing"

var oauth21Sections = []specSection{
	{Spec: "OAuth 2.1", Section: "1", Title: "Introduction", Notes: "Introductory material is not a test target."},
	{Spec: "OAuth 2.1", Section: "1.1", Title: "Roles", Notes: "Role definitions are not test targets."},
	{Spec: "OAuth 2.1", Section: "1.2", Title: "Protocol Flow", Notes: "Covered by section 4.1."},
	{Spec: "OAuth 2.1", Section: "1.3", Title: "Authorization Grant", Notes: "Covered by the applicable subsections below."},
	{Spec: "OAuth 2.1", Section: "1.3.1", Title: "Authorization Code", Applicable: true, Run: testOAuth21AuthorizationCodeGrant},
	{Spec: "OAuth 2.1", Section: "1.3.2", Title: "Refresh Token", Notes: "Covered by sections 4.3, 4.3.1, 4.3.2, and 4.3.3."},
	{Spec: "OAuth 2.1", Section: "1.3.3", Title: "Client Credentials", Notes: "Covered by sections 4.2 and 4.2.1."},
	{Spec: "OAuth 2.1", Section: "1.4", Title: "Access Token", Applicable: true, Run: testOAuth21AccessTokenValidation},
	{Spec: "OAuth 2.1", Section: "1.4.1", Title: "Access Token Scope", Applicable: true, Notes: "An authorization request without scope fails with invalid_request instead of invalid_scope, as covered by OIDC Core 1.0 section 3.1.2.2; scope is optional for client credentials and refresh requests.", Run: testOAuth21AccessTokenScope},
	{Spec: "OAuth 2.1", Section: "1.4.2", Title: "Bearer Tokens", Notes: "Bearer token usage is covered by sections 5.1, 5.1.1, 5.1.2, 5.2, 5.3.1, and 5.3.2, and access token signing by RFC 9068 section 2.1; TLS is out of scope."},
	{Spec: "OAuth 2.1", Section: "1.4.3", Title: "Sender-Constrained Access Tokens", Notes: "Sender-constrained access tokens are not implemented."},
	{Spec: "OAuth 2.1", Section: "1.5", Title: "Communication security", Notes: "TLS is out of scope."},
	{Spec: "OAuth 2.1", Section: "1.6", Title: "HTTP Redirections", Notes: "Covered by section 7.5.3."},
	{Spec: "OAuth 2.1", Section: "1.7", Title: "Interoperability", Notes: "Interoperability guidance is not a test target."},
	{Spec: "OAuth 2.1", Section: "1.8", Title: "Compatibility with OAuth 2.0", Notes: "PKCE is covered by section 7.5.1.1, the removed Implicit and password grants by sections 10.1 and 3.2.4, and exact redirect URI matching by section 2.3.5."},
	{Spec: "OAuth 2.1", Section: "1.9", Title: "Notational Conventions", Notes: "Notation guidance is not a test target."},
	{Spec: "OAuth 2.1", Section: "2", Title: "Client Registration", Notes: "Covered by the applicable subsections below."},
	{Spec: "OAuth 2.1", Section: "2.1", Title: "Client Types", Applicable: true, Run: testOAuth21ClientTypes},
	{Spec: "OAuth 2.1", Section: "2.2", Title: "Client Identifier", Applicable: true, Run: testOAuth21ClientIdentifier},
	{Spec: "OAuth 2.1", Section: "2.3", Title: "Client Redirection Endpoint", Notes: "Covered by the applicable subsections below; configured redirect URIs must be absolute without fragments. Registered query parameters are retained in success and error responses, as covered by sections 2.3.2 and 4.1.2.1."},
	{Spec: "OAuth 2.1", Section: "2.3.1", Title: "Registration Requirements", Notes: "Redirect URIs are validated at startup; exact matching and loopback port variation are covered by sections 2.3.5 and 8.4.2."},
	{Spec: "OAuth 2.1", Section: "2.3.2", Title: "Multiple Redirect URIs", Applicable: true, Notes: "The redirect_uri parameter is required even with a single registered URI, because OIDC Core 1.0 section 3.1.2.1 requires it; loopback port variation is covered by section 8.4.2.", Run: testOAuth21MultipleRedirectURIs},
	{Spec: "OAuth 2.1", Section: "2.3.3", Title: "Preventing CSRF Attacks", Applicable: true, Notes: "Choosing among state, nonce, and PKCE is client behavior; the product round-trips state and requires PKCE.", Run: testOAuth21PreventingCSRFAttacks},
	{Spec: "OAuth 2.1", Section: "2.3.4", Title: "Preventing Mix-Up Attacks", Applicable: true, Run: testOAuth21PreventingMixUpAttacks},
	{Spec: "OAuth 2.1", Section: "2.3.5", Title: "Invalid Endpoint", Applicable: true, Run: testOAuth21InvalidEndpoint},
	{Spec: "OAuth 2.1", Section: "2.3.6", Title: "Endpoint Content", Notes: "This section describes client behavior."},
	{Spec: "OAuth 2.1", Section: "2.4", Title: "Client Authentication", Applicable: true, Run: testClientAuthentication},
	{Spec: "OAuth 2.1", Section: "2.4.1", Title: "Client Secret", Applicable: true, Notes: "Basic credential form encoding is covered for client IDs and secrets containing spaces, plus signs, percent signs, and colons; brute-force protection for client secrets is not implemented.", Run: testTokenRequest},
	{Spec: "OAuth 2.1", Section: "2.4.2", Title: "Other Authentication Methods", Notes: "Other client authentication methods are not implemented."},
	{Spec: "OAuth 2.1", Section: "2.5", Title: "Unregistered Clients", Notes: "Rejection of unregistered clients is covered by section 2.2."},
	{Spec: "OAuth 2.1", Section: "3", Title: "Protocol Endpoints", Notes: "Covered by the applicable subsections below."},
	{Spec: "OAuth 2.1", Section: "3.1", Title: "Authorization Endpoint", Applicable: true, Notes: "Rejection of duplicate recognized parameters and ignoring repeated unrecognized parameters in GET and POST requests are covered by OIDC Core 1.0 section 3.1.2.2. Response parameters appearing at most once are covered by sections 4.1.2 and 4.1.2.1.", Run: testOAuth21AuthorizationEndpoint},
	{Spec: "OAuth 2.1", Section: "3.2", Title: "Token Endpoint", Notes: "Covered by the applicable subsections below; CORS is not implemented. Rejection of duplicate recognized parameters and ignoring repeated unrecognized parameters across supported grants are covered by section 3.2.4."},
	{Spec: "OAuth 2.1", Section: "3.2.1", Title: "Client Authentication", Applicable: true, Run: testClientAuthentication},
	{Spec: "OAuth 2.1", Section: "3.2.2", Title: "Token Endpoint Request", Applicable: true, Run: testTokenRequest},
	{Spec: "OAuth 2.1", Section: "3.2.3", Title: "Token Endpoint Response", Applicable: true, Notes: "The ID Token is covered by OIDC Core 1.0 sections 3.1.3.3 and 3.1.3.6.", Run: testOAuth21TokenEndpointResponse},
	{Spec: "OAuth 2.1", Section: "3.2.4", Title: "Token Endpoint Error Response", Applicable: true, Run: testTokenErrorResponse},
	{Spec: "OAuth 2.1", Section: "4", Title: "Grant Types", Notes: "Covered by the applicable subsections below."},
	{Spec: "OAuth 2.1", Section: "4.1", Title: "Authorization Code Grant", Applicable: true, Run: testOAuth21AuthorizationCodeGrant},
	{Spec: "OAuth 2.1", Section: "4.1.1", Title: "Authorization Request", Notes: "Authorization requests are covered by OIDC Core 1.0 sections 3.1.2.1 and 3.1.2.2, and loopback port variation by section 8.4.2; the product only supports the S256 code challenge method."},
	{Spec: "OAuth 2.1", Section: "4.1.2", Title: "Authorization Response", Applicable: true, Notes: "End-user authentication and consent are covered by OIDC Core 1.0 sections 3.1.2.3 and 3.1.2.4. The product follows the recommended ten-minute maximum code lifetime; expiry rejection is covered by OIDC Core 1.0 section 3.1.3.2.", Run: testSuccessfulAuthenticationResponse},
	{Spec: "OAuth 2.1", Section: "4.1.2.1", Title: "Authorization Error Response", Applicable: true, Run: testOAuth21AuthorizationErrorResponse},
	{Spec: "OAuth 2.1", Section: "4.1.3", Title: "Token Endpoint Extension", Applicable: true, Run: testOAuth21TokenEndpointExtension},
	{Spec: "OAuth 2.1", Section: "4.2", Title: "Client Credentials Grant", Applicable: true, Run: testOAuth21ClientCredentialsGrant},
	{Spec: "OAuth 2.1", Section: "4.2.1", Title: "Token Endpoint Extension", Applicable: true, Run: testOAuth21ClientCredentialsRequest},
	{Spec: "OAuth 2.1", Section: "4.3", Title: "Refresh Token Grant", Applicable: true, Run: testOAuth21RefreshTokenGrant},
	{Spec: "OAuth 2.1", Section: "4.3.1", Title: "Token Endpoint Extension", Applicable: true, Run: testOAuth21RefreshTokenRequest},
	{Spec: "OAuth 2.1", Section: "4.3.2", Title: "Refresh Token Response", Applicable: true, Run: testOAuth21RefreshTokenResponse},
	{Spec: "OAuth 2.1", Section: "4.3.3", Title: "Refresh Token Recommendations", Applicable: true, Run: testOAuth21RefreshTokenRecommendations},
	{Spec: "OAuth 2.1", Section: "4.4", Title: "Extension Grants", Notes: "Extension grants are not implemented."},
	{Spec: "OAuth 2.1", Section: "5", Title: "Resource Requests", Notes: "Covered by the applicable subsections below."},
	{Spec: "OAuth 2.1", Section: "5.1", Title: "Bearer Token Requests", Applicable: true, Notes: "The header and form methods are covered by sections 5.1.1 and 5.1.2.", Run: testOAuth21BearerTokenRequests},
	{Spec: "OAuth 2.1", Section: "5.1.1", Title: "Authorization Request Header Field", Applicable: true, Run: testOAuth21BearerAuthorizationHeaderField},
	{Spec: "OAuth 2.1", Section: "5.1.2", Title: "Form-Encoded Content Parameter", Applicable: true, Run: testOAuth21FormEncodedContentParameter},
	{Spec: "OAuth 2.1", Section: "5.2", Title: "Access Token Validation", Applicable: true, Run: testOAuth21AccessTokenValidation},
	{Spec: "OAuth 2.1", Section: "5.3", Title: "Error Response", Notes: "Covered by the applicable subsections below."},
	{Spec: "OAuth 2.1", Section: "5.3.1", Title: "The WWW-Authenticate Response Header Field", Applicable: true, Run: testOAuth21WWWAuthenticateResponseHeaderField},
	{Spec: "OAuth 2.1", Section: "5.3.2", Title: "Error Codes", Applicable: true, Notes: "UserInfo, the product's only protected resource, returns invalid_request for malformed requests, invalid_token for unknown or expired access tokens, and insufficient_scope for access tokens without the openid scope.", Run: testOAuth21ErrorCodes},
	{Spec: "OAuth 2.1", Section: "6", Title: "Extensibility", Notes: "See the subsections below."},
	{Spec: "OAuth 2.1", Section: "6.1", Title: "Defining Access Token Types", Notes: "Extensibility rules are not test targets."},
	{Spec: "OAuth 2.1", Section: "6.1.1", Title: "Registered Access Token Types", Notes: "Extensibility rules are not test targets."},
	{Spec: "OAuth 2.1", Section: "6.1.2", Title: "Vendor-Specific Access Token Types", Notes: "Vendor-specific access token types are not implemented."},
	{Spec: "OAuth 2.1", Section: "6.2", Title: "Defining New Endpoint Parameters", Notes: "Extensibility rules are not test targets."},
	{Spec: "OAuth 2.1", Section: "6.3", Title: "Defining New Authorization Grant Types", Notes: "Extension grants are not implemented."},
	{Spec: "OAuth 2.1", Section: "6.4", Title: "Defining New Authorization Endpoint Response Types", Notes: "Extension response types are not implemented."},
	{Spec: "OAuth 2.1", Section: "6.5", Title: "Defining Additional Error Codes", Notes: "Extensibility rules are not test targets."},
	{Spec: "OAuth 2.1", Section: "7", Title: "Security Considerations", Notes: "Covered by the applicable subsections below."},
	{Spec: "OAuth 2.1", Section: "7.1", Title: "Access Token Security Considerations", Notes: "Covered by the applicable subsections below."},
	{Spec: "OAuth 2.1", Section: "7.1.1", Title: "Security Threats", Notes: "See the subsections below."},
	{Spec: "OAuth 2.1", Section: "7.1.1.1", Title: "Access token manufacture/modification", Notes: "Access token signing is covered by RFC 9068 section 2.1."},
	{Spec: "OAuth 2.1", Section: "7.1.1.2", Title: "Access token information disclosure", Notes: "Bearer tokens in cookies are covered by section 7.1.3.4; access token encryption is not implemented, and TLS is out of scope."},
	{Spec: "OAuth 2.1", Section: "7.1.1.3", Title: "Access token redirect", Notes: "Audience restriction is covered by RFC 9068 section 3, and scope restriction by section 1.4.1; UserInfo does not check the audience."},
	{Spec: "OAuth 2.1", Section: "7.1.1.4", Title: "Access token replay", Notes: "Sender-constrained access tokens are not implemented; short-lived bearer tokens are covered by section 7.1.3.5."},
	{Spec: "OAuth 2.1", Section: "7.1.2", Title: "Threat Mitigation", Notes: "Signing and audience restriction are covered by RFC 9068 sections 2.1 and 3, and introspection by RFC 7662 section 2."},
	{Spec: "OAuth 2.1", Section: "7.1.3", Title: "Summary of Recommendations", Notes: "Covered by the applicable subsections below."},
	{Spec: "OAuth 2.1", Section: "7.1.3.1", Title: "Safeguard bearer tokens", Notes: "This section describes client behavior."},
	{Spec: "OAuth 2.1", Section: "7.1.3.2", Title: "Validate TLS certificate chains", Notes: "This section describes client behavior, and TLS is out of scope."},
	{Spec: "OAuth 2.1", Section: "7.1.3.3", Title: "Always use TLS (https)", Notes: "TLS is out of scope."},
	{Spec: "OAuth 2.1", Section: "7.1.3.4", Title: "Don't store bearer tokens in HTTP cookies", Applicable: true, Run: testOAuth21DontStoreBearerTokensInHTTPCookies},
	{Spec: "OAuth 2.1", Section: "7.1.3.5", Title: "Issue short-lived bearer tokens", Applicable: true, Notes: "As provider policy, the access and ID token lifetime must be a whole number of seconds, so expires_in always equals exp minus iat.", Run: testOAuth21IssueShortLivedBearerTokens},
	{Spec: "OAuth 2.1", Section: "7.1.3.6", Title: "Issue scoped bearer tokens", Notes: "Audience restriction is covered by RFC 9068 section 3; UserInfo does not check the audience."},
	{Spec: "OAuth 2.1", Section: "7.1.3.7", Title: "Don't pass bearer tokens in page URLs", Applicable: true, Run: testOAuth21DontPassBearerTokensInPageURLs},
	{Spec: "OAuth 2.1", Section: "7.1.4", Title: "Access Token Privilege Restriction", Notes: "Audience restriction is covered by RFC 9068 section 3, and scope restriction by section 1.4.1; UserInfo does not check the audience."},
	{Spec: "OAuth 2.1", Section: "7.2", Title: "Client Authentication", Notes: "Client trust guidance is not a test target."},
	{Spec: "OAuth 2.1", Section: "7.3", Title: "Client Impersonation", Notes: "Sessions are only reused without end-user interaction for confidential clients, which authenticate at the token endpoint; public clients are covered by section 7.3.1."},
	{Spec: "OAuth 2.1", Section: "7.3.1", Title: "Impersonation of Native Apps", Applicable: true, Notes: "Platform identity proofs, such as claimed https redirects, are not implemented.", Run: testOAuth21ImpersonationOfNativeApps},
	{Spec: "OAuth 2.1", Section: "7.3.2", Title: "Access Token Privilege Restriction", Notes: "Audience restriction is covered by RFC 9068 section 3, and scope restriction by section 1.4.1; UserInfo does not check the audience."},
	{Spec: "OAuth 2.1", Section: "7.4", Title: "Client Impersonating Resource Owner", Notes: "Clients are operator-configured, so a client cannot choose a client_id that poses as an end-user."},
	{Spec: "OAuth 2.1", Section: "7.5", Title: "Authorization Code Security Considerations", Notes: "Covered by the applicable subsections below."},
	{Spec: "OAuth 2.1", Section: "7.5.1", Title: "Authorization Code Injection", Notes: "Covered by the applicable subsections below."},
	{Spec: "OAuth 2.1", Section: "7.5.1.1", Title: "Countermeasures", Applicable: true, Notes: "PKCE is required for all clients, even confidential clients that send a nonce; code_verifier checks are covered by OIDC Core 1.0 section 3.1.3.2.", Run: testOAuth21AuthorizationCodeInjectionCountermeasures},
	{Spec: "OAuth 2.1", Section: "7.5.2", Title: "Reuse of Authorization Codes", Applicable: true, Run: testOAuth21ReuseOfAuthorizationCodes},
	{Spec: "OAuth 2.1", Section: "7.5.3", Title: "HTTP 307 Redirect", Applicable: true, Run: testHTTP307Redirects},
	{Spec: "OAuth 2.1", Section: "7.6", Title: "Ensuring Endpoint Authenticity", Notes: "TLS is out of scope."},
	{Spec: "OAuth 2.1", Section: "7.7", Title: "Credentials-Guessing Attacks", Notes: "Credential entropy is not a test target, and brute-force protection for passwords and client secrets is not implemented."},
	{Spec: "OAuth 2.1", Section: "7.8", Title: "Phishing Attacks", Notes: "Phishing guidance is not a test target, and TLS is out of scope."},
	{Spec: "OAuth 2.1", Section: "7.9", Title: "Cross-Site Request Forgery", Applicable: true, Run: testOAuth21PreventingCSRFAttacks},
	{Spec: "OAuth 2.1", Section: "7.10", Title: "Clickjacking", Applicable: true, Run: testOAuth21Clickjacking},
	{Spec: "OAuth 2.1", Section: "7.11", Title: "Injection and Input Validation", Applicable: true, Run: testOAuth21InjectionAndInputValidation},
	{Spec: "OAuth 2.1", Section: "7.12", Title: "Open Redirection", Notes: "See the subsections below."},
	{Spec: "OAuth 2.1", Section: "7.12.1", Title: "Client as Open Redirector", Notes: "This section describes client behavior."},
	{Spec: "OAuth 2.1", Section: "7.12.2", Title: "Authorization Server as Open Redirector", Notes: "Invalid redirect URIs are covered by section 2.3.5; error responses are redirected before the end-user authenticates, but clients are operator-configured, so attackers cannot register phishing redirect URIs."},
	{Spec: "OAuth 2.1", Section: "7.13", Title: "Transport Security", Notes: "TLS is out of scope."},
	{Spec: "OAuth 2.1", Section: "7.14", Title: "Authorization Server Mix-Up Mitigation", Applicable: true, Run: testOAuth21MixUpDefenseViaIssuerIdentification},
	{Spec: "OAuth 2.1", Section: "7.14.1", Title: "Mix-Up Defense via Issuer Identification", Applicable: true, Run: testOAuth21MixUpDefenseViaIssuerIdentification},
	{Spec: "OAuth 2.1", Section: "7.14.2", Title: "Mix-Up Defense via Distinct Redirect URIs", Notes: "This section describes client behavior; issuer identification is covered by section 7.14.1."},
	{Spec: "OAuth 2.1", Section: "8", Title: "Native Applications", Notes: "Covered by the applicable subsections below."},
	{Spec: "OAuth 2.1", Section: "8.1", Title: "Client Authentication of Native Apps", Applicable: true, Run: testOAuth21ClientAuthenticationOfNativeApps},
	{Spec: "OAuth 2.1", Section: "8.1.1", Title: "Registration of Native App Clients", Applicable: true, Run: testOAuth21RegistrationOfNativeAppClients},
	{Spec: "OAuth 2.1", Section: "8.1.2", Title: "Native App Attestation", Notes: "Native app attestation is not implemented."},
	{Spec: "OAuth 2.1", Section: "8.2", Title: "Using Inter-App URI Communication for OAuth in Native Apps", Notes: "This section describes client behavior; loopback redirects are covered by section 8.4.2."},
	{Spec: "OAuth 2.1", Section: "8.3", Title: "Initiating the Authorization Request from a Native App", Notes: "This section describes client behavior."},
	{Spec: "OAuth 2.1", Section: "8.4", Title: "Receiving the Authorization Response in a Native App", Notes: "Covered by the applicable subsections below."},
	{Spec: "OAuth 2.1", Section: "8.4.1", Title: "Claimed \"https\" Scheme URI Redirection", Notes: "The product only supports loopback redirects for native clients."},
	{Spec: "OAuth 2.1", Section: "8.4.2", Title: "Loopback Interface Redirection", Applicable: true, Run: testOAuth21LoopbackInterfaceRedirection},
	{Spec: "OAuth 2.1", Section: "8.4.3", Title: "Private-Use URI Scheme Redirection", Notes: "The product only supports loopback redirects for native clients."},
	{Spec: "OAuth 2.1", Section: "8.5", Title: "Security Considerations in Native Apps", Notes: "Covered by the applicable subsections below."},
	{Spec: "OAuth 2.1", Section: "8.5.1", Title: "Embedded User Agents in Native Apps", Notes: "Threat descriptions are not test targets."},
	{Spec: "OAuth 2.1", Section: "8.5.2", Title: "Fake External User-Agents in Native Apps", Notes: "Threat descriptions are not test targets."},
	{Spec: "OAuth 2.1", Section: "8.5.3", Title: "Malicious External User-Agents in Native Apps", Notes: "Threat descriptions are not test targets."},
	{Spec: "OAuth 2.1", Section: "8.5.4", Title: "Loopback Redirect Considerations in Native Apps", Applicable: true, Run: testOAuth21LoopbackRedirectConsiderations},
	{Spec: "OAuth 2.1", Section: "9", Title: "Browser-Based Apps", Notes: "Placeholder text is not a test target."},
	{Spec: "OAuth 2.1", Section: "10", Title: "Differences from OAuth 2.0", Notes: "Covered by the applicable subsections below."},
	{Spec: "OAuth 2.1", Section: "10.1", Title: "Removal of the OAuth 2.0 Implicit grant", Applicable: true, Run: testOAuth21RemovalOfImplicitGrant},
	{Spec: "OAuth 2.1", Section: "10.2", Title: "Redirect URI Parameter in Token Request", Applicable: true, Run: testOAuth21RedirectURIParameterInTokenRequest},
	{Spec: "OAuth 2.1", Section: "11", Title: "IANA Considerations", Notes: "IANA registration text is not a test target."},
	{Spec: "OAuth 2.1", Section: "12", Title: "References", Notes: "Reference sections are not test targets."},
	{Spec: "OAuth 2.1", Section: "12.1", Title: "Normative References", Notes: "Reference sections are not test targets."},
	{Spec: "OAuth 2.1", Section: "12.2", Title: "Informative References", Notes: "Reference sections are not test targets."},
	{Spec: "OAuth 2.1", Section: "A", Title: "Augmented Backus-Naur Form (ABNF) Syntax", Notes: "See the subsections below."},
	{Spec: "OAuth 2.1", Section: "A.1", Title: "\"client_id\" Syntax", Notes: "Printable ASCII credential samples and their Basic form encoding are covered by section 2.4.1; the full grammar is not tested."},
	{Spec: "OAuth 2.1", Section: "A.2", Title: "\"client_secret\" Syntax", Notes: "Printable ASCII credential samples and their Basic form encoding are covered by section 2.4.1; the full grammar is not tested."},
	{Spec: "OAuth 2.1", Section: "A.3", Title: "\"response_type\" Syntax", Notes: "Only the code response type is supported; acceptance and unsupported response types are covered by OIDC Core 1.0 sections 3.1.2.1 and 3.1.2.2, and section 10.1; the full grammar is not tested."},
	{Spec: "OAuth 2.1", Section: "A.4", Title: "\"scope\" Syntax", Notes: "Space-separated scope handling is covered by sections 1.4.1 and 4.3.1; the full grammar is not tested."},
	{Spec: "OAuth 2.1", Section: "A.5", Title: "\"state\" Syntax", Notes: "ASCII state with spaces and reserved URI characters is covered by appendix C.1; the full grammar is not tested."},
	{Spec: "OAuth 2.1", Section: "A.6", Title: "\"redirect_uri\" Syntax", Notes: "Matching registered URIs and preserving their query parameters are covered by sections 2.3.2 and 2.3.5; the product requires configured redirect URIs to be absolute and fragment-free; the full grammar is not tested."},
	{Spec: "OAuth 2.1", Section: "A.7", Title: "\"error\" Syntax", Notes: "Emitted error codes are covered by sections 4.1.2.1, 3.2.4, and 5.3.2; the full grammar is not tested."},
	{Spec: "OAuth 2.1", Section: "A.8", Title: "\"error_description\" Syntax", Notes: "Emitted error descriptions are covered by section 4.1.2.1; the full grammar is not tested."},
	{Spec: "OAuth 2.1", Section: "A.9", Title: "\"error_uri\" Syntax", Notes: "The optional error_uri parameter is not emitted."},
	{Spec: "OAuth 2.1", Section: "A.10", Title: "\"grant_type\" Syntax", Notes: "The authorization_code, refresh_token, and client_credentials grants are covered by sections 4.1, 4.3, and 4.2, and unsupported grants by section 3.2.4; extension grants are not implemented; the full grammar is not tested."},
	{Spec: "OAuth 2.1", Section: "A.11", Title: "\"code\" Syntax", Notes: "Authorization code issuance and use are covered by sections 4.1.2 and 4.1.3; the full grammar is not tested."},
	{Spec: "OAuth 2.1", Section: "A.12", Title: "\"access_token\" Syntax", Notes: "The JWT access token form is covered by RFC 9068 sections 2.1 and 2.2; other access token formats are not implemented; the full grammar is not tested."},
	{Spec: "OAuth 2.1", Section: "A.13", Title: "\"token_type\" Syntax", Notes: "The Bearer token type is covered by section 3.2.3; extension token types are not implemented; the full grammar is not tested."},
	{Spec: "OAuth 2.1", Section: "A.14", Title: "\"expires_in\" Syntax", Notes: "Integer token lifetime values are covered by sections 3.2.3 and 7.1.3.5, and numeric JSON serialization by appendix C.3; the full grammar is not tested."},
	{Spec: "OAuth 2.1", Section: "A.15", Title: "\"refresh_token\" Syntax", Notes: "Refresh token issuance and use are covered by sections 3.2.3 and 4.3; the full grammar is not tested."},
	{Spec: "OAuth 2.1", Section: "A.16", Title: "Endpoint Parameter Syntax", Notes: "Extensibility rules are not test targets."},
	{Spec: "OAuth 2.1", Section: "A.17", Title: "\"code_verifier\" Syntax", Notes: "Missing, short, malformed, and mismatched verifiers are covered by OIDC Core 1.0 section 3.1.3.2; the full grammar is not tested."},
	{Spec: "OAuth 2.1", Section: "A.18", Title: "\"code_challenge\" Syntax", Notes: "S256 challenges and missing or unsupported PKCE parameters are covered by OIDC Core 1.0 section 3.1.2.2 and section 7.5.1.1; the full grammar is not tested."},
	{Spec: "OAuth 2.1", Section: "B", Title: "Use of application/x-www-form-urlencoded Media Type", Applicable: true, Notes: "UTF-8 and reserved characters from the appendix's example round-trip in an OIDC nonce; Basic credential encoding is covered by section 2.4.1.", Run: testFormSerialization},
	{Spec: "OAuth 2.1", Section: "C", Title: "Serializations", Notes: "Covered by the applicable subsections below."},
	{Spec: "OAuth 2.1", Section: "C.1", Title: "Query String Serialization", Applicable: true, Run: testQuerySerialization},
	{Spec: "OAuth 2.1", Section: "C.2", Title: "Form-Encoded Serialization", Applicable: true, Run: testFormSerialization},
	{Spec: "OAuth 2.1", Section: "C.3", Title: "JSON Serialization", Applicable: true, Run: testJSONSerialization},
	{Spec: "OAuth 2.1", Section: "D", Title: "Extensions", Notes: "This appendix catalogs extensions rather than defining them. Token revocation, introspection, and JWT access tokens have separate RFC 7009, RFC 7662, and RFC 9068 manifests; issuer identification is covered by section 7.14.1."},
	{Spec: "OAuth 2.1", Section: "E", Title: "Acknowledgements", Notes: "Acknowledgements are not test targets."},
	{Spec: "OAuth 2.1", Section: "F", Title: "Document History", Notes: "Draft history is not a test target."},
}

func TestOAuth21Sections(t *testing.T) {
	runSpecSections(t, oauth21Sections)
}
