package simpleidp

// Reference material:
// OIDC Core 1.0: https://openid.net/specs/openid-connect-core-1_0.html

import "testing"

var oidcCoreSections = []specSection{
	{Spec: "OIDC Core 1.0", Section: "1", Title: "Introduction", Notes: "Introductory material is not a direct integration-test target."},
	{Spec: "OIDC Core 1.0", Section: "1.1", Title: "Requirements Notation and Conventions", Notes: "Notation guidance is not a direct runtime integration-test target."},
	{Spec: "OIDC Core 1.0", Section: "1.2", Title: "Terminology", Notes: "Terminology definitions are reflected by the executable sections below rather than tested independently."},
	{Spec: "OIDC Core 1.0", Section: "1.3", Title: "Overview", Notes: "Overview text summarizes behavior that is exercised by the concrete flow, claims, and UserInfo sections below."},
	{Spec: "OIDC Core 1.0", Section: "2", Title: "ID Token", Applicable: true, Notes: "JWT structure and core claims are covered; the product currently permits local http issuers, so the specification's https issuer requirement is not claimed as conformant here.", Run: testIDToken},
	{Spec: "OIDC Core 1.0", Section: "3", Title: "Authentication", Notes: "Concrete authentication behavior is covered by the documented flow-specific subsections below."},
	{Spec: "OIDC Core 1.0", Section: "3.1", Title: "Authentication using the Authorization Code Flow", Notes: "Concrete authorization code flow behavior is covered by the applicable subsections below."},
	{Spec: "OIDC Core 1.0", Section: "3.1.1", Title: "Authorization Code Flow Steps", Applicable: true, Run: testAuthorizationCodeFlowSteps},
	{Spec: "OIDC Core 1.0", Section: "3.1.2", Title: "Authorization Endpoint", Notes: "Authorization endpoint behavior is covered by the applicable request and response subsections below."},
	{Spec: "OIDC Core 1.0", Section: "3.1.2.1", Title: "Authentication Request", Applicable: true, Run: testAuthenticationRequest},
	{Spec: "OIDC Core 1.0", Section: "3.1.2.2", Title: "Authentication Request Validation", Applicable: true, Run: testAuthenticationRequestValidation},
	{Spec: "OIDC Core 1.0", Section: "3.1.2.3", Title: "Authorization Server Authenticates End-User", Applicable: true, Run: testAuthorizationServerAuthenticatesEndUser},
	{Spec: "OIDC Core 1.0", Section: "3.1.2.4", Title: "Authorization Server Obtains End-User Consent/Authorization", Applicable: true, Run: testAuthorizationServerObtainsEndUserConsentAuthorization},
	{Spec: "OIDC Core 1.0", Section: "3.1.2.5", Title: "Successful Authentication Response", Applicable: true, Run: testSuccessfulAuthenticationResponse},
	{Spec: "OIDC Core 1.0", Section: "3.1.2.6", Title: "Authentication Error Response", Applicable: true, Run: testAuthenticationErrorResponse},
	{Spec: "OIDC Core 1.0", Section: "3.1.2.7", Title: "Authentication Response Validation", Notes: "This is RP-side validation behavior. Provider redirect-shape sanity remains covered by TestOIDCProviderOutputSanity without claiming direct conformance coverage for RP validation."},
	{Spec: "OIDC Core 1.0", Section: "3.1.3", Title: "Token Endpoint", Notes: "Token endpoint behavior is covered by the applicable token-processing subsections below."},
	{Spec: "OIDC Core 1.0", Section: "3.1.3.1", Title: "Token Request", Applicable: true, Run: testTokenRequest},
	{Spec: "OIDC Core 1.0", Section: "3.1.3.2", Title: "Token Request Validation", Applicable: true, Run: testTokenRequestValidation},
	{Spec: "OIDC Core 1.0", Section: "3.1.3.3", Title: "Successful Token Response", Applicable: true, Run: testSuccessfulTokenResponse},
	{Spec: "OIDC Core 1.0", Section: "3.1.3.4", Title: "Token Error Response", Applicable: true, Run: testTokenErrorResponse},
	{Spec: "OIDC Core 1.0", Section: "3.1.3.5", Title: "Token Response Validation", Notes: "This is RP-side validation behavior. Provider token-output sanity remains covered by TestOIDCProviderOutputSanity without claiming direct conformance coverage for RP validation."},
	{Spec: "OIDC Core 1.0", Section: "3.1.3.6", Title: "ID Token", Applicable: true, Notes: "Token-endpoint ID Token contents are covered; the product currently permits local http issuers, so the specification's https issuer requirement is not claimed as conformant here.", Run: testTokenEndpointIDToken},
	{Spec: "OIDC Core 1.0", Section: "3.1.3.7", Title: "ID Token Validation", Notes: "This is RP-side validation behavior. Provider signing and claim-shape sanity remains covered by TestOIDCProviderOutputSanity without claiming direct conformance coverage for RP validation."},
	{Spec: "OIDC Core 1.0", Section: "3.1.3.8", Title: "Access Token Validation", Notes: "This is RP-side validation behavior. Provider at_hash consistency remains covered by TestOIDCProviderOutputSanity without claiming direct conformance coverage for RP validation."},
	{Spec: "OIDC Core 1.0", Section: "3.2", Title: "Authentication using the Implicit Flow", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.2.1", Title: "Implicit Flow Steps", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2", Title: "Authorization Endpoint", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2.1", Title: "Authentication Request", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2.2", Title: "Authentication Request Validation", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2.3", Title: "Authorization Server Authenticates End-User", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2.4", Title: "Authorization Server Obtains End-User Consent/Authorization", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2.5", Title: "Successful Authentication Response", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2.6", Title: "Authentication Error Response", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2.7", Title: "Redirect URI Fragment Handling", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2.8", Title: "Authentication Response Validation", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2.9", Title: "Access Token Validation", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2.10", Title: "ID Token", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2.11", Title: "ID Token Validation", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3", Title: "Authentication using the Hybrid Flow", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.1", Title: "Hybrid Flow Steps", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2", Title: "Authorization Endpoint", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.1", Title: "Authentication Request", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.2", Title: "Authentication Request Validation", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.3", Title: "Authorization Server Authenticates End-User", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.4", Title: "Authorization Server Obtains End-User Consent/Authorization", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.5", Title: "Successful Authentication Response", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.6", Title: "Authentication Error Response", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.7", Title: "Redirect URI Fragment Handling", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.8", Title: "Authentication Response Validation", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.9", Title: "Access Token Validation", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.10", Title: "Authorization Code Validation", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.11", Title: "ID Token", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.12", Title: "ID Token Validation", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.3", Title: "Token Endpoint", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.3.1", Title: "Token Request", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.3.2", Title: "Token Request Validation", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.3.3", Title: "Successful Token Response", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.3.4", Title: "Token Error Response", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.3.5", Title: "Token Response Validation", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.3.6", Title: "ID Token", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.3.7", Title: "ID Token Validation", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.3.8", Title: "Access Token", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "3.3.3.9", Title: "Access Token Validation", Notes: "The product only supports the Authorization Code Flow with PKCE."},
	{Spec: "OIDC Core 1.0", Section: "4", Title: "Initiating Login from a Third Party", Notes: "Third-party initiated login is RP-side behavior and is not implemented by this provider."},
	{Spec: "OIDC Core 1.0", Section: "5", Title: "Claims", Notes: "Claims behavior is covered by the documented subsections below."},
	{Spec: "OIDC Core 1.0", Section: "5.1", Title: "Standard Claims", Applicable: true, Run: testStandardClaims},
	{Spec: "OIDC Core 1.0", Section: "5.1.1", Title: "Address Claim", Notes: "The product does not implement the address scope or address claim set."},
	{Spec: "OIDC Core 1.0", Section: "5.1.2", Title: "Additional Claims", Notes: "Additional claims are product-specific; the suite exercises the custom groups claim without treating this extensibility section as a standalone conformance target."},
	{Spec: "OIDC Core 1.0", Section: "5.2", Title: "Claims Languages and Scripts", Notes: "Localized claim variants are not implemented; ui_locales and claims_locales are only tolerated as ignored inputs."},
	{Spec: "OIDC Core 1.0", Section: "5.3", Title: "UserInfo Endpoint", Notes: "UserInfo endpoint behavior is covered by the applicable subsections below."},
	{Spec: "OIDC Core 1.0", Section: "5.3.1", Title: "UserInfo Request", Applicable: true, Run: testUserInfoRequest},
	{Spec: "OIDC Core 1.0", Section: "5.3.2", Title: "Successful UserInfo Response", Applicable: true, Run: testSuccessfulUserInfoResponse},
	{Spec: "OIDC Core 1.0", Section: "5.3.3", Title: "UserInfo Error Response", Applicable: true, Notes: "The single UserInfo resource exercised by this suite surfaces invalid_request and invalid_token; it does not expose a separate higher-privilege variant that would trigger insufficient_scope.", Run: testUserInfoErrorResponse},
	{Spec: "OIDC Core 1.0", Section: "5.3.4", Title: "UserInfo Response Validation", Notes: "This is RP-side validation behavior. Provider subject-consistency sanity remains covered by TestOIDCProviderOutputSanity without claiming direct conformance coverage for RP validation."},
	{Spec: "OIDC Core 1.0", Section: "5.4", Title: "Requesting Claims using Scope Values", Applicable: true, Notes: "The suite covers the implemented profile and email scope values from this section; address and phone scope values are not implemented by this product.", Run: testScopeBasedClaims},
	{Spec: "OIDC Core 1.0", Section: "5.5", Title: "Requesting Claims using the \"claims\" Request Parameter", Notes: "The product does not support the claims request parameter."},
	{Spec: "OIDC Core 1.0", Section: "5.5.1", Title: "Individual Claims Requests", Notes: "The product does not support the claims request parameter."},
	{Spec: "OIDC Core 1.0", Section: "5.5.1.1", Title: "Requesting the \"acr\" Claim", Notes: "The product does not support the claims request parameter."},
	{Spec: "OIDC Core 1.0", Section: "5.5.2", Title: "Languages and Scripts for Individual Claims", Notes: "The product does not support the claims request parameter."},
	{Spec: "OIDC Core 1.0", Section: "5.6", Title: "Claim Types", Notes: "Claim-type behavior is covered by the documented subsections below."},
	{Spec: "OIDC Core 1.0", Section: "5.6.1", Title: "Normal Claims", Applicable: true, Run: testNormalClaims},
	{Spec: "OIDC Core 1.0", Section: "5.6.2", Title: "Aggregated and Distributed Claims", Notes: "The product returns only normal JSON claims."},
	{Spec: "OIDC Core 1.0", Section: "5.6.2.1", Title: "Example of Aggregated Claims", Notes: "Example sections are not direct runtime integration-test targets."},
	{Spec: "OIDC Core 1.0", Section: "5.6.2.2", Title: "Example of Distributed Claims", Notes: "Example sections are not direct runtime integration-test targets."},
	{Spec: "OIDC Core 1.0", Section: "5.7", Title: "Claim Stability and Uniqueness", Applicable: true, Run: testClaimStabilityAndUniqueness},
	{Spec: "OIDC Core 1.0", Section: "6", Title: "Passing Request Parameters as JWTs", Notes: "The product intentionally rejects request and request_uri parameters instead of supporting Request Objects."},
	{Spec: "OIDC Core 1.0", Section: "6.1", Title: "Passing a Request Object by Value", Notes: "The product does not support Request Objects or the request and request_uri parameters."},
	{Spec: "OIDC Core 1.0", Section: "6.1.1", Title: "Request using the \"request\" Request Parameter", Notes: "The product does not support Request Objects or the request and request_uri parameters."},
	{Spec: "OIDC Core 1.0", Section: "6.2", Title: "Passing a Request Object by Reference", Notes: "The product does not support Request Objects or the request and request_uri parameters."},
	{Spec: "OIDC Core 1.0", Section: "6.2.1", Title: "URI Referencing the Request Object", Notes: "The product does not support Request Objects or the request and request_uri parameters."},
	{Spec: "OIDC Core 1.0", Section: "6.2.2", Title: "Request using the \"request_uri\" Request Parameter", Notes: "The product does not support Request Objects or the request and request_uri parameters."},
	{Spec: "OIDC Core 1.0", Section: "6.2.3", Title: "Authorization Server Fetches Request Object", Notes: "The product does not support Request Objects or the request and request_uri parameters."},
	{Spec: "OIDC Core 1.0", Section: "6.2.4", Title: "\"request_uri\" Rationale", Notes: "The product does not support Request Objects or the request and request_uri parameters."},
	{Spec: "OIDC Core 1.0", Section: "6.3", Title: "Validating JWT-Based Requests", Notes: "The product does not support Request Objects or the request and request_uri parameters."},
	{Spec: "OIDC Core 1.0", Section: "6.3.1", Title: "Encrypted Request Object", Notes: "The product does not support Request Objects or the request and request_uri parameters."},
	{Spec: "OIDC Core 1.0", Section: "6.3.2", Title: "Signed Request Object", Notes: "The product does not support Request Objects or the request and request_uri parameters."},
	{Spec: "OIDC Core 1.0", Section: "6.3.3", Title: "Request Parameter Assembly and Validation", Notes: "The product does not support Request Objects or the request and request_uri parameters."},
	{Spec: "OIDC Core 1.0", Section: "7", Title: "Self-Issued OpenID Provider", Notes: "This provider is not self-issued."},
	{Spec: "OIDC Core 1.0", Section: "7.1", Title: "Self-Issued OpenID Provider Discovery", Notes: "This provider is not self-issued."},
	{Spec: "OIDC Core 1.0", Section: "7.2", Title: "Self-Issued OpenID Provider Registration", Notes: "This provider is not self-issued."},
	{Spec: "OIDC Core 1.0", Section: "7.2.1", Title: "Providing Information with the \"registration\" Request Parameter", Notes: "This provider is not self-issued."},
	{Spec: "OIDC Core 1.0", Section: "7.3", Title: "Self-Issued OpenID Provider Request", Notes: "This provider is not self-issued."},
	{Spec: "OIDC Core 1.0", Section: "7.4", Title: "Self-Issued OpenID Provider Response", Notes: "This provider is not self-issued."},
	{Spec: "OIDC Core 1.0", Section: "7.5", Title: "Self-Issued ID Token Validation", Notes: "This provider is not self-issued."},
	{Spec: "OIDC Core 1.0", Section: "8", Title: "Subject Identifier Types", Applicable: true, Run: testSubjectIdentifierTypes},
	{Spec: "OIDC Core 1.0", Section: "8.1", Title: "Pairwise Identifier Algorithm", Notes: "The product supports public subject identifiers only."},
	{Spec: "OIDC Core 1.0", Section: "9", Title: "Client Authentication", Applicable: true, Run: testClientAuthentication},
	{Spec: "OIDC Core 1.0", Section: "10", Title: "Signatures and Encryption", Notes: "Signing behavior is covered by the applicable subsection below; encryption is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "10.1", Title: "Signing", Applicable: true, Run: testSigning},
	{Spec: "OIDC Core 1.0", Section: "10.1.1", Title: "Rotation of Asymmetric Signing Keys", Notes: "The product exposes a single signing key and does not implement signing-key rotation."},
	{Spec: "OIDC Core 1.0", Section: "10.2", Title: "Encryption", Notes: "The product does not implement encrypted ID Tokens or encrypted responses."},
	{Spec: "OIDC Core 1.0", Section: "10.2.1", Title: "Rotation of Asymmetric Encryption Keys", Notes: "The product does not implement encrypted ID Tokens or encryption-key rotation."},
	{Spec: "OIDC Core 1.0", Section: "11", Title: "Offline Access", Notes: "The product issues refresh tokens for online access but does not implement the offline_access scope."},
	{Spec: "OIDC Core 1.0", Section: "12", Title: "Using Refresh Tokens", Notes: "Refresh-token behavior is covered by the applicable request, response, and error subsections below."},
	{Spec: "OIDC Core 1.0", Section: "12.1", Title: "Refresh Request", Applicable: true, Run: testRefreshRequest},
	{Spec: "OIDC Core 1.0", Section: "12.2", Title: "Successful Refresh Response", Applicable: true, Run: testSuccessfulRefreshResponse},
	{Spec: "OIDC Core 1.0", Section: "12.3", Title: "Refresh Error Response", Applicable: true, Run: testRefreshErrorResponse},
	{Spec: "OIDC Core 1.0", Section: "13", Title: "Serializations", Notes: "Concrete query, form, and JSON serializations are covered by the applicable subsections below."},
	{Spec: "OIDC Core 1.0", Section: "13.1", Title: "Query String Serialization", Applicable: true, Run: testQuerySerialization},
	{Spec: "OIDC Core 1.0", Section: "13.2", Title: "Form Serialization", Applicable: true, Run: testFormSerialization},
	{Spec: "OIDC Core 1.0", Section: "13.3", Title: "JSON Serialization", Applicable: true, Run: testJSONSerialization},
	{Spec: "OIDC Core 1.0", Section: "14", Title: "String Operations", Applicable: true, Run: testStringOperations},
	{Spec: "OIDC Core 1.0", Section: "15", Title: "Implementation Considerations", Notes: "Concrete mandatory-to-implement requirements and implementation guidance are covered by the applicable or documented subsections below."},
	{Spec: "OIDC Core 1.0", Section: "15.1", Title: "Mandatory to Implement Features for All OpenID Providers", Applicable: true, Run: testMandatoryToImplementFeaturesForAllOpenIDProviders},
	{Spec: "OIDC Core 1.0", Section: "15.2", Title: "Mandatory to Implement Features for Dynamic OpenID Providers", Notes: "Dynamic client registration is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "15.3", Title: "Discovery and Registration", Notes: "Discovery and logout are covered by separate spec suites."},
	{Spec: "OIDC Core 1.0", Section: "15.4", Title: "Mandatory to Implement Features for Relying Parties", Notes: "This suite targets provider behavior, not relying-party behavior."},
	{Spec: "OIDC Core 1.0", Section: "15.5", Title: "Implementation Notes", Notes: "Implementation-note guidance is covered by the documented subsections below."},
	{Spec: "OIDC Core 1.0", Section: "15.5.1", Title: "Authorization Code Implementation Notes", Notes: "Authorization code handling guidance is exercised by the authorization-code, token-validation, and token-reuse tests."},
	{Spec: "OIDC Core 1.0", Section: "15.5.2", Title: "Nonce Implementation Notes", Notes: "Nonce handling guidance is exercised by the ID Token and authentication-request tests."},
	{Spec: "OIDC Core 1.0", Section: "15.5.3", Title: "Redirect URI Fragment Handling Implementation Notes", Notes: "Fragment handling is not applicable to the backend-only authorization code flow."},
	{Spec: "OIDC Core 1.0", Section: "15.6", Title: "Compatibility Notes", Notes: "Compatibility notes are informational and not direct integration-test targets."},
	{Spec: "OIDC Core 1.0", Section: "15.7", Title: "Related Specifications and Implementer's Guides", Notes: "Related-specification pointers are informational and not direct integration-test targets."},
	{Spec: "OIDC Core 1.0", Section: "16", Title: "Security Considerations", Notes: "Concrete security behaviors are either covered by the applicable subsections below or documented as out of scope where they depend on unsupported features or transport security."},
	{Spec: "OIDC Core 1.0", Section: "16.1", Title: "Request Disclosure", Notes: "Request-disclosure mitigations that depend on signed or encrypted Request Objects are not implemented; transport security is documented separately as out of scope."},
	{Spec: "OIDC Core 1.0", Section: "16.2", Title: "Server Masquerading", Notes: "Issuer consistency and discovery-based server identification are covered by the discovery and authentication-response validation suites."},
	{Spec: "OIDC Core 1.0", Section: "16.3", Title: "Token Manufacture/Modification", Notes: "ID Token signing and validation cover token manufacture or modification defenses for the signed artifacts this product issues."},
	{Spec: "OIDC Core 1.0", Section: "16.4", Title: "Access Token Disclosure", Notes: "Bearer-token disclosure mitigations are exercised by the OAuth 2.1 bearer-token security tests; transport security is documented separately as out of scope."},
	{Spec: "OIDC Core 1.0", Section: "16.5", Title: "Server Response Disclosure", Notes: "Response-disclosure risks tied to transport security are out of scope in the loopback harness; cache-control protections are exercised elsewhere in the suite."},
	{Spec: "OIDC Core 1.0", Section: "16.6", Title: "Server Response Repudiation", Notes: "Signed ID Tokens provide response non-repudiation for the authentication artifacts this product issues."},
	{Spec: "OIDC Core 1.0", Section: "16.7", Title: "Request Repudiation", Notes: "Signed Request Objects are not supported, so request-repudiation guidance is not a separate runtime target."},
	{Spec: "OIDC Core 1.0", Section: "16.8", Title: "Access Token Redirect", Notes: "Access tokens are bound to the issuing client and validated at resource endpoints; the concrete checks are exercised elsewhere in the suite."},
	{Spec: "OIDC Core 1.0", Section: "16.9", Title: "Token Reuse", Applicable: true, Run: testTokenReuse},
	{Spec: "OIDC Core 1.0", Section: "16.10", Title: "Eavesdropping or Leaking Authorization Codes (Secondary Authenticator Capture)", Notes: "Authorization code leakage defenses are exercised through redirect-uri binding, code-verifier validation, and code-reuse rejection."},
	{Spec: "OIDC Core 1.0", Section: "16.11", Title: "Token Substitution", Notes: "UserInfo response validation and subject matching guard against token substitution and are exercised elsewhere in the suite."},
	{Spec: "OIDC Core 1.0", Section: "16.12", Title: "Timing Attack", Notes: "Constant-time comparison is an implementation detail and not a direct black-box integration-test target."},
	{Spec: "OIDC Core 1.0", Section: "16.13", Title: "Other Crypto Related Attacks", Notes: "General cryptographic hardening guidance is broader than this suite's black-box runtime surface."},
	{Spec: "OIDC Core 1.0", Section: "16.14", Title: "Signing and Encryption Order", Notes: "The product signs ID Tokens but does not implement encrypted responses, so signing and encryption ordering is not applicable."},
	{Spec: "OIDC Core 1.0", Section: "16.15", Title: "Issuer Identifier", Notes: "Issuer consistency is exercised by discovery validation and authorization-response issuer checks in the suite."},
	{Spec: "OIDC Core 1.0", Section: "16.16", Title: "Implicit Flow Threats", Notes: "The product does not support the Implicit Flow."},
	{Spec: "OIDC Core 1.0", Section: "16.17", Title: "TLS Requirements", Notes: "HTTPS enforcement is explicitly out of scope for this task."},
	{Spec: "OIDC Core 1.0", Section: "16.18", Title: "Lifetimes of Access Tokens and Refresh Tokens", Notes: "Short-lived access-token behavior is exercised by the bearer-token lifetime tests; refresh-token lifetime and replay protections are exercised by the refresh-token request, response, and recommendation tests."},
	{Spec: "OIDC Core 1.0", Section: "16.19", Title: "Symmetric Key Entropy", Notes: "Symmetric-key entropy requirements are configuration concerns and not direct black-box integration-test targets."},
	{Spec: "OIDC Core 1.0", Section: "16.20", Title: "Need for Signed Requests", Notes: "Signed Request Objects are not supported."},
	{Spec: "OIDC Core 1.0", Section: "16.21", Title: "Need for Encrypted Requests", Notes: "Encrypted Request Objects are not supported."},
	{Spec: "OIDC Core 1.0", Section: "16.22", Title: "HTTP 307 Redirects", Applicable: true, Run: testHTTP307Redirects},
	{Spec: "OIDC Core 1.0", Section: "16.23", Title: "Custom URI Schemes on iOS", Notes: "The product only supports loopback redirects for native clients and does not implement custom URI schemes on iOS."},
	{Spec: "OIDC Core 1.0", Section: "17", Title: "Privacy Considerations", Notes: "Privacy guidance is informational and not a direct integration-test target for this product."},
	{Spec: "OIDC Core 1.0", Section: "17.1", Title: "Personally Identifiable Information", Notes: "PII consent policy is product- and jurisdiction-specific; the suite covers prompt=consent behavior elsewhere."},
	{Spec: "OIDC Core 1.0", Section: "17.2", Title: "Data Access Monitoring", Notes: "The product does not provide end-user access logs."},
	{Spec: "OIDC Core 1.0", Section: "17.3", Title: "Correlation", Notes: "The product does not implement pairwise subject identifiers."},
	{Spec: "OIDC Core 1.0", Section: "17.4", Title: "Offline Access", Notes: "The product issues refresh tokens for online access but does not implement the offline_access scope."},
	{Spec: "OIDC Core 1.0", Section: "18", Title: "IANA Considerations", Notes: "IANA registration text is not a runtime integration-test target."},
	{Spec: "OIDC Core 1.0", Section: "18.1", Title: "JSON Web Token Claims Registration", Notes: "IANA registration text is not a runtime integration-test target."},
	{Spec: "OIDC Core 1.0", Section: "18.1.1", Title: "Registry Contents", Notes: "IANA registration text is not a runtime integration-test target."},
	{Spec: "OIDC Core 1.0", Section: "18.2", Title: "OAuth Parameters Registration", Notes: "IANA registration text is not a runtime integration-test target."},
	{Spec: "OIDC Core 1.0", Section: "18.2.1", Title: "Registry Contents", Notes: "IANA registration text is not a runtime integration-test target."},
	{Spec: "OIDC Core 1.0", Section: "18.3", Title: "OAuth Extensions Error Registration", Notes: "IANA registration text is not a runtime integration-test target."},
	{Spec: "OIDC Core 1.0", Section: "18.3.1", Title: "Registry Contents", Notes: "IANA registration text is not a runtime integration-test target."},
	{Spec: "OIDC Core 1.0", Section: "18.4", Title: "URI Scheme Registration", Notes: "IANA registration text is not a runtime integration-test target."},
	{Spec: "OIDC Core 1.0", Section: "18.4.1", Title: "Registry Contents", Notes: "IANA registration text is not a runtime integration-test target."},
	{Spec: "OIDC Core 1.0", Section: "19", Title: "References", Notes: "Reference sections are not runtime integration-test targets."},
	{Spec: "OIDC Core 1.0", Section: "19.1", Title: "Normative References", Notes: "Reference sections are not runtime integration-test targets."},
	{Spec: "OIDC Core 1.0", Section: "19.2", Title: "Informative References", Notes: "Reference sections are not runtime integration-test targets."},
}

func TestOIDCCoreSections(t *testing.T) {
	runSpecSections(t, oidcCoreSections)
}
