package simpleidp

// Reference material:
// OIDC Core 1.0: https://openid.net/specs/openid-connect-core-1_0.html

import "testing"

var oidcCoreSections = []specSection{
	{Spec: "OIDC Core 1.0", Section: "1", Title: "Introduction", Notes: "Introductory material is not a test target."},
	{Spec: "OIDC Core 1.0", Section: "1.1", Title: "Requirements Notation and Conventions", Notes: "Notation guidance is not a test target."},
	{Spec: "OIDC Core 1.0", Section: "1.2", Title: "Terminology", Notes: "Terminology definitions are not test targets."},
	{Spec: "OIDC Core 1.0", Section: "1.3", Title: "Overview", Notes: "Covered by section 3.1.1."},
	{Spec: "OIDC Core 1.0", Section: "2", Title: "ID Token", Applicable: true, Notes: "Issuer URL components and subject ASCII and length constraints are validated at startup. As provider policy, user info is rejected in issuer URLs and auth_time is always included, even without max_age. TLS is out of scope, so the issuer may use http.", Run: testIDToken},
	{Spec: "OIDC Core 1.0", Section: "3", Title: "Authentication", Notes: "Covered by the applicable subsections below."},
	{Spec: "OIDC Core 1.0", Section: "3.1", Title: "Authentication using the Authorization Code Flow", Notes: "Covered by the applicable subsections below."},
	{Spec: "OIDC Core 1.0", Section: "3.1.1", Title: "Authorization Code Flow Steps", Applicable: true, Run: testAuthorizationCodeFlowSteps},
	{Spec: "OIDC Core 1.0", Section: "3.1.2", Title: "Authorization Endpoint", Notes: "Covered by the applicable subsections below; TLS is out of scope."},
	{Spec: "OIDC Core 1.0", Section: "3.1.2.1", Title: "Authentication Request", Applicable: true, Notes: "Loopback redirect URIs of public clients may use http and any port, following OAuth 2.1 section 8.4.2.", Run: testAuthenticationRequest},
	{Spec: "OIDC Core 1.0", Section: "3.1.2.2", Title: "Authentication Request Validation", Applicable: true, Notes: "The authorization endpoint only supports OIDC requests and requires the openid scope; unsupported response modes are rejected without redirection. As provider policy, unrecognized prompt values are rejected with invalid_request.", Run: testAuthenticationRequestValidation},
	{Spec: "OIDC Core 1.0", Section: "3.1.2.3", Title: "Authorization Server Authenticates End-User", Applicable: true, Notes: "As provider policy, prompt accepts surrounding whitespace beyond the specification's space separator; select_account renders a login form.", Run: testAuthorizationServerAuthenticatesEndUser},
	{Spec: "OIDC Core 1.0", Section: "3.1.2.4", Title: "Authorization Server Obtains End-User Consent/Authorization", Applicable: true, Run: testAuthorizationServerObtainsEndUserConsentAuthorization},
	{Spec: "OIDC Core 1.0", Section: "3.1.2.5", Title: "Successful Authentication Response", Applicable: true, Run: testSuccessfulAuthenticationResponse},
	{Spec: "OIDC Core 1.0", Section: "3.1.2.6", Title: "Authentication Error Response", Applicable: true, Run: testAuthenticationErrorResponse},
	{Spec: "OIDC Core 1.0", Section: "3.1.2.7", Title: "Authentication Response Validation", Notes: "This section describes RP behavior; the authentication response it validates is covered by section 3.1.2.5."},
	{Spec: "OIDC Core 1.0", Section: "3.1.3", Title: "Token Endpoint", Notes: "Covered by the applicable subsections below; TLS is out of scope."},
	{Spec: "OIDC Core 1.0", Section: "3.1.3.1", Title: "Token Request", Applicable: true, Run: testTokenRequest},
	{Spec: "OIDC Core 1.0", Section: "3.1.3.2", Title: "Token Request Validation", Applicable: true, Notes: "The redirect_uri parameter may be omitted even with several registered redirect URIs, as covered by OAuth 2.1 section 10.2. Codes expire within the recommended ten-minute maximum of OAuth 2.1 section 4.1.2; as provider policy, redemption also requires a live browser session.", Run: testTokenRequestValidation},
	{Spec: "OIDC Core 1.0", Section: "3.1.3.3", Title: "Successful Token Response", Applicable: true, Notes: "As provider policy, successful authorization code exchanges always issue a refresh token.", Run: testSuccessfulTokenResponse},
	{Spec: "OIDC Core 1.0", Section: "3.1.3.4", Title: "Token Error Response", Applicable: true, Run: testTokenErrorResponse},
	{Spec: "OIDC Core 1.0", Section: "3.1.3.5", Title: "Token Response Validation", Notes: "This section describes RP behavior; the token response it validates is covered by sections 3.1.3.3 and 3.1.3.6."},
	{Spec: "OIDC Core 1.0", Section: "3.1.3.6", Title: "ID Token", Applicable: true, Notes: "As provider policy, ID Tokens always include the optional at_hash claim; refreshed ID Tokens are covered by section 12.2. TLS is out of scope, so the issuer may use http.", Run: testTokenEndpointIDToken},
	{Spec: "OIDC Core 1.0", Section: "3.1.3.7", Title: "ID Token Validation", Notes: "This section describes RP behavior; the ID Token it validates is covered by sections 2, 3.1.3.6, and 10.1."},
	{Spec: "OIDC Core 1.0", Section: "3.1.3.8", Title: "Access Token Validation", Notes: "This section describes RP behavior; the at_hash it relies on is covered by section 3.1.3.6."},
	{Spec: "OIDC Core 1.0", Section: "3.2", Title: "Authentication using the Implicit Flow", Notes: "The Implicit Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.2.1", Title: "Implicit Flow Steps", Notes: "The Implicit Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2", Title: "Authorization Endpoint", Notes: "The Implicit Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2.1", Title: "Authentication Request", Notes: "The Implicit Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2.2", Title: "Authentication Request Validation", Notes: "The Implicit Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2.3", Title: "Authorization Server Authenticates End-User", Notes: "The Implicit Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2.4", Title: "Authorization Server Obtains End-User Consent/Authorization", Notes: "The Implicit Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2.5", Title: "Successful Authentication Response", Notes: "The Implicit Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2.6", Title: "Authentication Error Response", Notes: "The Implicit Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2.7", Title: "Redirect URI Fragment Handling", Notes: "The Implicit Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2.8", Title: "Authentication Response Validation", Notes: "The Implicit Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2.9", Title: "Access Token Validation", Notes: "The Implicit Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2.10", Title: "ID Token", Notes: "The Implicit Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.2.2.11", Title: "ID Token Validation", Notes: "The Implicit Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3", Title: "Authentication using the Hybrid Flow", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.1", Title: "Hybrid Flow Steps", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2", Title: "Authorization Endpoint", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.1", Title: "Authentication Request", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.2", Title: "Authentication Request Validation", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.3", Title: "Authorization Server Authenticates End-User", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.4", Title: "Authorization Server Obtains End-User Consent/Authorization", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.5", Title: "Successful Authentication Response", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.6", Title: "Authentication Error Response", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.7", Title: "Redirect URI Fragment Handling", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.8", Title: "Authentication Response Validation", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.9", Title: "Access Token Validation", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.10", Title: "Authorization Code Validation", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.11", Title: "ID Token", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.2.12", Title: "ID Token Validation", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.3", Title: "Token Endpoint", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.3.1", Title: "Token Request", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.3.2", Title: "Token Request Validation", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.3.3", Title: "Successful Token Response", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.3.4", Title: "Token Error Response", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.3.5", Title: "Token Response Validation", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.3.6", Title: "ID Token", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.3.7", Title: "ID Token Validation", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.3.8", Title: "Access Token", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "3.3.3.9", Title: "Access Token Validation", Notes: "The Hybrid Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "4", Title: "Initiating Login from a Third Party", Notes: "Third-party initiated login is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "5", Title: "Claims", Notes: "Covered by the applicable subsections below."},
	{Spec: "OIDC Core 1.0", Section: "5.1", Title: "Standard Claims", Applicable: true, Notes: "As provider policy, the email scope includes email_verified as a JSON boolean even when false, in ID Tokens, access tokens, UserInfo, and introspection responses; incomplete user configuration is rejected at startup.", Run: testStandardClaims},
	{Spec: "OIDC Core 1.0", Section: "5.1.1", Title: "Address Claim", Notes: "The address scope and claim are not implemented."},
	{Spec: "OIDC Core 1.0", Section: "5.1.2", Title: "Additional Claims", Applicable: true, Notes: "The groups and roles claims in access tokens are covered by RFC 9068 section 2.2.3.1, and in introspection responses by RFC 7662 section 5.", Run: testAdditionalClaims},
	{Spec: "OIDC Core 1.0", Section: "5.2", Title: "Claims Languages and Scripts", Notes: "Localized claims are not implemented; ui_locales and claims_locales are ignored."},
	{Spec: "OIDC Core 1.0", Section: "5.3", Title: "UserInfo Endpoint", Notes: "Covered by the applicable subsections below; CORS is not implemented, and TLS is out of scope."},
	{Spec: "OIDC Core 1.0", Section: "5.3.1", Title: "UserInfo Request", Applicable: true, Run: testUserInfoRequest},
	{Spec: "OIDC Core 1.0", Section: "5.3.2", Title: "Successful UserInfo Response", Applicable: true, Run: testSuccessfulUserInfoResponse},
	{Spec: "OIDC Core 1.0", Section: "5.3.3", Title: "UserInfo Error Response", Applicable: true, Notes: "UserInfo returns invalid_request for malformed requests, invalid_token for unknown or expired access tokens, and insufficient_scope for access tokens without the openid scope.", Run: testUserInfoErrorResponse},
	{Spec: "OIDC Core 1.0", Section: "5.3.4", Title: "UserInfo Response Validation", Notes: "This section describes RP behavior; the UserInfo response it validates is covered by section 5.3.2."},
	{Spec: "OIDC Core 1.0", Section: "5.4", Title: "Requesting Claims using Scope Values", Applicable: true, Notes: "The address and phone scopes are not implemented.", Run: testScopeBasedClaims},
	{Spec: "OIDC Core 1.0", Section: "5.5", Title: "Requesting Claims using the \"claims\" Request Parameter", Notes: "The claims request parameter is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "5.5.1", Title: "Individual Claims Requests", Notes: "The claims request parameter is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "5.5.1.1", Title: "Requesting the \"acr\" Claim", Notes: "The claims request parameter and the acr claim are not implemented; acr_values is ignored."},
	{Spec: "OIDC Core 1.0", Section: "5.5.2", Title: "Languages and Scripts for Individual Claims", Notes: "The claims request parameter is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "5.6", Title: "Claim Types", Notes: "Covered by the applicable subsections below."},
	{Spec: "OIDC Core 1.0", Section: "5.6.1", Title: "Normal Claims", Applicable: true, Run: testNormalClaims},
	{Spec: "OIDC Core 1.0", Section: "5.6.2", Title: "Aggregated and Distributed Claims", Notes: "Aggregated and distributed claims are not implemented."},
	{Spec: "OIDC Core 1.0", Section: "5.6.2.1", Title: "Example of Aggregated Claims", Notes: "Aggregated and distributed claims are not implemented."},
	{Spec: "OIDC Core 1.0", Section: "5.6.2.2", Title: "Example of Distributed Claims", Notes: "Aggregated and distributed claims are not implemented."},
	{Spec: "OIDC Core 1.0", Section: "5.7", Title: "Claim Stability and Uniqueness", Applicable: true, Notes: "Startup rejects duplicate configured subjects and configured subjects matching another user's default subject.", Run: testClaimStabilityAndUniqueness},
	{Spec: "OIDC Core 1.0", Section: "6", Title: "Passing Request Parameters as JWTs", Notes: "Request Objects are not implemented; the request and request_uri parameters are rejected."},
	{Spec: "OIDC Core 1.0", Section: "6.1", Title: "Passing a Request Object by Value", Notes: "Request Objects are not implemented."},
	{Spec: "OIDC Core 1.0", Section: "6.1.1", Title: "Request using the \"request\" Request Parameter", Notes: "Request Objects are not implemented."},
	{Spec: "OIDC Core 1.0", Section: "6.2", Title: "Passing a Request Object by Reference", Notes: "Request Objects are not implemented."},
	{Spec: "OIDC Core 1.0", Section: "6.2.1", Title: "URI Referencing the Request Object", Notes: "Request Objects are not implemented."},
	{Spec: "OIDC Core 1.0", Section: "6.2.2", Title: "Request using the \"request_uri\" Request Parameter", Notes: "Request Objects are not implemented."},
	{Spec: "OIDC Core 1.0", Section: "6.2.3", Title: "Authorization Server Fetches Request Object", Notes: "Request Objects are not implemented."},
	{Spec: "OIDC Core 1.0", Section: "6.2.4", Title: "\"request_uri\" Rationale", Notes: "Request Objects are not implemented."},
	{Spec: "OIDC Core 1.0", Section: "6.3", Title: "Validating JWT-Based Requests", Notes: "Request Objects are not implemented."},
	{Spec: "OIDC Core 1.0", Section: "6.3.1", Title: "Encrypted Request Object", Notes: "Request Objects are not implemented."},
	{Spec: "OIDC Core 1.0", Section: "6.3.2", Title: "Signed Request Object", Notes: "Request Objects are not implemented."},
	{Spec: "OIDC Core 1.0", Section: "6.3.3", Title: "Request Parameter Assembly and Validation", Notes: "Request Objects are not implemented."},
	{Spec: "OIDC Core 1.0", Section: "7", Title: "Self-Issued OpenID Provider", Notes: "The product is not a Self-Issued OpenID Provider."},
	{Spec: "OIDC Core 1.0", Section: "7.1", Title: "Self-Issued OpenID Provider Discovery", Notes: "The product is not a Self-Issued OpenID Provider."},
	{Spec: "OIDC Core 1.0", Section: "7.2", Title: "Self-Issued OpenID Provider Registration", Notes: "The product is not a Self-Issued OpenID Provider."},
	{Spec: "OIDC Core 1.0", Section: "7.2.1", Title: "Providing Information with the \"registration\" Request Parameter", Notes: "The product is not a Self-Issued OpenID Provider."},
	{Spec: "OIDC Core 1.0", Section: "7.3", Title: "Self-Issued OpenID Provider Request", Notes: "The product is not a Self-Issued OpenID Provider."},
	{Spec: "OIDC Core 1.0", Section: "7.4", Title: "Self-Issued OpenID Provider Response", Notes: "The product is not a Self-Issued OpenID Provider."},
	{Spec: "OIDC Core 1.0", Section: "7.5", Title: "Self-Issued ID Token Validation", Notes: "The product is not a Self-Issued OpenID Provider."},
	{Spec: "OIDC Core 1.0", Section: "8", Title: "Subject Identifier Types", Applicable: true, Run: testSubjectIdentifierTypes},
	{Spec: "OIDC Core 1.0", Section: "8.1", Title: "Pairwise Identifier Algorithm", Notes: "Pairwise subject identifiers are not implemented."},
	{Spec: "OIDC Core 1.0", Section: "9", Title: "Client Authentication", Applicable: true, Notes: "As provider policy, public clients must use client_id without authentication; both Basic authentication and form-body client secrets are rejected.", Run: testClientAuthentication},
	{Spec: "OIDC Core 1.0", Section: "10", Title: "Signatures and Encryption", Notes: "Covered by the applicable subsections below."},
	{Spec: "OIDC Core 1.0", Section: "10.1", Title: "Signing", Applicable: true, Notes: "RSA keys meet the required 2048-bit minimum. As provider policy, generated keys are 3072 bits, ID Tokens use typ JWT, and signed JWTs include a kid identifying the published signing key.", Run: testSigning},
	{Spec: "OIDC Core 1.0", Section: "10.1.1", Title: "Rotation of Asymmetric Signing Keys", Notes: "Signing key rotation is not implemented; the product uses a single signing key."},
	{Spec: "OIDC Core 1.0", Section: "10.2", Title: "Encryption", Notes: "Encryption is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "10.2.1", Title: "Rotation of Asymmetric Encryption Keys", Notes: "Encryption is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "11", Title: "Offline Access", Notes: "The offline_access scope is not implemented; refresh tokens are issued without it, do not expire with the session, and are revoked at logout."},
	{Spec: "OIDC Core 1.0", Section: "12", Title: "Using Refresh Tokens", Notes: "Covered by the applicable subsections below."},
	{Spec: "OIDC Core 1.0", Section: "12.1", Title: "Refresh Request", Applicable: true, Run: testRefreshRequest},
	{Spec: "OIDC Core 1.0", Section: "12.2", Title: "Successful Refresh Response", Applicable: true, Notes: "As provider policy, the product returns a refreshed ID Token whenever the refreshed scope includes openid and rotates confidential-client refresh tokens. It follows the recommendation to omit nonce from refreshed ID Tokens.", Run: testSuccessfulRefreshResponse},
	{Spec: "OIDC Core 1.0", Section: "12.3", Title: "Refresh Error Response", Applicable: true, Run: testRefreshErrorResponse},
	{Spec: "OIDC Core 1.0", Section: "13", Title: "Serializations", Notes: "Covered by the applicable subsections below."},
	{Spec: "OIDC Core 1.0", Section: "13.1", Title: "Query String Serialization", Applicable: true, Run: testQuerySerialization},
	{Spec: "OIDC Core 1.0", Section: "13.2", Title: "Form Serialization", Applicable: true, Run: testFormSerialization},
	{Spec: "OIDC Core 1.0", Section: "13.3", Title: "JSON Serialization", Applicable: true, Run: testJSONSerialization},
	{Spec: "OIDC Core 1.0", Section: "14", Title: "String Operations", Applicable: true, Run: testStringOperations},
	{Spec: "OIDC Core 1.0", Section: "15", Title: "Implementation Considerations", Notes: "Covered by the applicable subsections below."},
	{Spec: "OIDC Core 1.0", Section: "15.1", Title: "Mandatory to Implement Features for All OpenID Providers", Applicable: true, Run: testMandatoryToImplementFeaturesForAllOpenIDProviders},
	{Spec: "OIDC Core 1.0", Section: "15.2", Title: "Mandatory to Implement Features for Dynamic OpenID Providers", Notes: "Dynamic client registration is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "15.3", Title: "Discovery and Registration", Notes: "Discovery is covered by OIDC Discovery 1.0 sections 3, 4.1, 4.2, and 4.3; dynamic client registration is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "15.4", Title: "Mandatory to Implement Features for Relying Parties", Notes: "This section describes RP behavior."},
	{Spec: "OIDC Core 1.0", Section: "15.5", Title: "Implementation Notes", Notes: "See the subsections below."},
	{Spec: "OIDC Core 1.0", Section: "15.5.1", Title: "Authorization Code Implementation Notes", Notes: "Authorization code storage is not a test target."},
	{Spec: "OIDC Core 1.0", Section: "15.5.2", Title: "Nonce Implementation Notes", Notes: "This section describes RP behavior; the nonce round trip is covered by section 2."},
	{Spec: "OIDC Core 1.0", Section: "15.5.3", Title: "Redirect URI Fragment Handling Implementation Notes", Notes: "The product only supports the query response mode."},
	{Spec: "OIDC Core 1.0", Section: "15.6", Title: "Compatibility Notes", Notes: "Compatibility notes are not test targets."},
	{Spec: "OIDC Core 1.0", Section: "15.7", Title: "Related Specifications and Implementer's Guides", Notes: "Pointers to related specifications are not test targets."},
	{Spec: "OIDC Core 1.0", Section: "16", Title: "Security Considerations", Notes: "Covered by the applicable subsections below."},
	{Spec: "OIDC Core 1.0", Section: "16.1", Title: "Request Disclosure", Notes: "Request Objects are not implemented, and TLS is out of scope."},
	{Spec: "OIDC Core 1.0", Section: "16.2", Title: "Server Masquerading", Notes: "Signing is covered by section 10.1, and TLS is out of scope."},
	{Spec: "OIDC Core 1.0", Section: "16.3", Title: "Token Manufacture/Modification", Notes: "Signing is covered by section 10.1, and TLS is out of scope."},
	{Spec: "OIDC Core 1.0", Section: "16.4", Title: "Access Token Disclosure", Notes: "Bearer token handling is covered by OAuth 2.1 sections 7.1.3.4 and 7.1.3.7, and TLS is out of scope."},
	{Spec: "OIDC Core 1.0", Section: "16.5", Title: "Server Response Disclosure", Notes: "The product only supports the code response type, and TLS is out of scope."},
	{Spec: "OIDC Core 1.0", Section: "16.6", Title: "Server Response Repudiation", Notes: "Signing is covered by section 10.1."},
	{Spec: "OIDC Core 1.0", Section: "16.7", Title: "Request Repudiation", Notes: "Request Objects are not implemented."},
	{Spec: "OIDC Core 1.0", Section: "16.8", Title: "Access Token Redirect", Notes: "Audience restriction is covered by RFC 9068 section 3, and scope restriction by OAuth 2.1 section 1.4.1; UserInfo does not check the audience."},
	{Spec: "OIDC Core 1.0", Section: "16.9", Title: "Token Reuse", Applicable: true, Run: testTokenReuse},
	{Spec: "OIDC Core 1.0", Section: "16.10", Title: "Eavesdropping or Leaking Authorization Codes (Secondary Authenticator Capture)", Notes: "Client authentication is covered by section 9, and PKCE by sections 3.1.2.2 and 3.1.3.2."},
	{Spec: "OIDC Core 1.0", Section: "16.11", Title: "Token Substitution", Notes: "This section describes RP behavior; the ID Token claims it relies on are covered by sections 2 and 3.1.3.6."},
	{Spec: "OIDC Core 1.0", Section: "16.12", Title: "Timing Attack", Notes: "Timing behavior is not a test target."},
	{Spec: "OIDC Core 1.0", Section: "16.13", Title: "Other Crypto Related Attacks", Notes: "General cryptographic guidance is not a test target."},
	{Spec: "OIDC Core 1.0", Section: "16.14", Title: "Signing and Encryption Order", Notes: "Encryption is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "16.15", Title: "Issuer Identifier", Notes: "Issuer consistency, including issuer paths, is covered by OIDC Discovery 1.0 section 4.3."},
	{Spec: "OIDC Core 1.0", Section: "16.16", Title: "Implicit Flow Threats", Notes: "The Implicit Flow is not implemented."},
	{Spec: "OIDC Core 1.0", Section: "16.17", Title: "TLS Requirements", Notes: "TLS is out of scope."},
	{Spec: "OIDC Core 1.0", Section: "16.18", Title: "Lifetimes of Access Tokens and Refresh Tokens", Notes: "Short-lived access tokens are covered by OAuth 2.1 section 7.1.3.5, and refresh tokens by OAuth 2.1 sections 4.3, 4.3.1, 4.3.2, and 4.3.3; long-term grants are not highlighted, and end-users can only revoke tokens by logging out."},
	{Spec: "OIDC Core 1.0", Section: "16.19", Title: "Symmetric Key Entropy", Notes: "Symmetric signing and encryption are not implemented."},
	{Spec: "OIDC Core 1.0", Section: "16.20", Title: "Need for Signed Requests", Notes: "Request Objects are not implemented."},
	{Spec: "OIDC Core 1.0", Section: "16.21", Title: "Need for Encrypted Requests", Notes: "Request Objects are not implemented."},
	{Spec: "OIDC Core 1.0", Section: "16.22", Title: "HTTP 307 Redirects", Applicable: true, Run: testHTTP307Redirects},
	{Spec: "OIDC Core 1.0", Section: "16.23", Title: "Custom URI Schemes on iOS", Notes: "The product only supports loopback redirects for native clients, as covered by OAuth 2.1 section 8.4.2."},
	{Spec: "OIDC Core 1.0", Section: "17", Title: "Privacy Considerations", Notes: "See the subsections below."},
	{Spec: "OIDC Core 1.0", Section: "17.1", Title: "Personally Identifiable Information", Notes: "Consent is covered by section 3.1.2.4."},
	{Spec: "OIDC Core 1.0", Section: "17.2", Title: "Data Access Monitoring", Notes: "End-user access logs are not implemented."},
	{Spec: "OIDC Core 1.0", Section: "17.3", Title: "Correlation", Notes: "Pairwise subject identifiers are not implemented."},
	{Spec: "OIDC Core 1.0", Section: "17.4", Title: "Offline Access", Notes: "The offline_access scope is not implemented; refresh tokens are issued without it, do not expire with the session, and are revoked at logout."},
	{Spec: "OIDC Core 1.0", Section: "18", Title: "IANA Considerations", Notes: "IANA registration text is not a test target."},
	{Spec: "OIDC Core 1.0", Section: "18.1", Title: "JSON Web Token Claims Registration", Notes: "IANA registration text is not a test target."},
	{Spec: "OIDC Core 1.0", Section: "18.1.1", Title: "Registry Contents", Notes: "IANA registration text is not a test target."},
	{Spec: "OIDC Core 1.0", Section: "18.2", Title: "OAuth Parameters Registration", Notes: "IANA registration text is not a test target."},
	{Spec: "OIDC Core 1.0", Section: "18.2.1", Title: "Registry Contents", Notes: "IANA registration text is not a test target."},
	{Spec: "OIDC Core 1.0", Section: "18.3", Title: "OAuth Extensions Error Registration", Notes: "IANA registration text is not a test target."},
	{Spec: "OIDC Core 1.0", Section: "18.3.1", Title: "Registry Contents", Notes: "IANA registration text is not a test target."},
	{Spec: "OIDC Core 1.0", Section: "18.4", Title: "URI Scheme Registration", Notes: "IANA registration text is not a test target."},
	{Spec: "OIDC Core 1.0", Section: "18.4.1", Title: "Registry Contents", Notes: "IANA registration text is not a test target."},
	{Spec: "OIDC Core 1.0", Section: "19", Title: "References", Notes: "Reference sections are not test targets."},
	{Spec: "OIDC Core 1.0", Section: "19.1", Title: "Normative References", Notes: "Reference sections are not test targets."},
	{Spec: "OIDC Core 1.0", Section: "19.2", Title: "Informative References", Notes: "Reference sections are not test targets."},
	{Spec: "OIDC Core 1.0", Section: "A", Title: "Authorization Examples", Notes: "Examples are not test targets."},
	{Spec: "OIDC Core 1.0", Section: "A.1", Title: "Example using response_type=code", Notes: "Examples are not test targets."},
	{Spec: "OIDC Core 1.0", Section: "A.2", Title: "Example using response_type=id_token", Notes: "Examples are not test targets."},
	{Spec: "OIDC Core 1.0", Section: "A.3", Title: "Example using response_type=id_token token", Notes: "Examples are not test targets."},
	{Spec: "OIDC Core 1.0", Section: "A.4", Title: "Example using response_type=code id_token", Notes: "Examples are not test targets."},
	{Spec: "OIDC Core 1.0", Section: "A.5", Title: "Example using response_type=code token", Notes: "Examples are not test targets."},
	{Spec: "OIDC Core 1.0", Section: "A.6", Title: "Example using response_type=code id_token token", Notes: "Examples are not test targets."},
	{Spec: "OIDC Core 1.0", Section: "A.7", Title: "RSA Key Used in Examples", Notes: "Examples are not test targets."},
	{Spec: "OIDC Core 1.0", Section: "B", Title: "Acknowledgements", Notes: "Acknowledgements are not test targets."},
	{Spec: "OIDC Core 1.0", Section: "C", Title: "Notices", Notes: "Notices are not test targets."},
}

func TestOIDCCoreSections(t *testing.T) {
	runSpecSections(t, oidcCoreSections)
}
