package simpleidp

// Reference material:
// OAuth 2.1 draft 15: https://www.ietf.org/archive/id/draft-ietf-oauth-v2-1-15.txt

import "testing"

var oauth21Sections = []specSection{
	{Spec: "OAuth 2.1", Section: "1", Title: "Introduction", Notes: "Introductory material is not a direct integration-test target."},
	{Spec: "OAuth 2.1", Section: "1.1", Title: "Roles", Notes: "Role definitions are not directly exercised by integration tests."},
	{Spec: "OAuth 2.1", Section: "1.2", Title: "Protocol Flow", Notes: "The concrete authorization code flow is covered by later executable sections."},
	{Spec: "OAuth 2.1", Section: "1.3", Title: "Authorization Grant", Notes: "The implemented grant-specific behavior is covered by the concrete subsections below."},
	{Spec: "OAuth 2.1", Section: "1.3.1", Title: "Authorization Code", Applicable: true, Run: testOAuth21AuthorizationCodeGrant},
	{Spec: "OAuth 2.1", Section: "1.3.2", Title: "Refresh Token", Notes: "This overview section is exercised by the concrete refresh-grant sections 4.3 through 4.3.3 rather than a standalone black-box test."},
	{Spec: "OAuth 2.1", Section: "1.3.3", Title: "Client Credentials", Notes: "The client credentials grant is not implemented."},
	{Spec: "OAuth 2.1", Section: "1.4", Title: "Access Token", Applicable: true, Run: testOAuth21AccessTokenValidation},
	{Spec: "OAuth 2.1", Section: "1.4.1", Title: "Access Token Scope", Applicable: true, Run: testOAuth21AccessTokenScope},
	{Spec: "OAuth 2.1", Section: "1.4.2", Title: "Bearer Tokens", Notes: "Concrete bearer-token transmission, validation, and error handling are covered by sections 5.1.1, 5.1.2, 5.2, 5.3.1, and 5.3.2."},
	{Spec: "OAuth 2.1", Section: "1.4.3", Title: "Sender-Constrained Access Tokens", Notes: "Sender-constrained access tokens are not implemented."},
	{Spec: "OAuth 2.1", Section: "1.5", Title: "Communication security", Notes: "HTTPS enforcement is explicitly out of scope for this task."},
	{Spec: "OAuth 2.1", Section: "1.6", Title: "HTTP Redirections", Notes: "Redirect handling is covered by the concrete authorization-code and security sections."},
	{Spec: "OAuth 2.1", Section: "1.7", Title: "Interoperability", Notes: "Interoperability guidance is informational and not a direct integration-test target."},
	{Spec: "OAuth 2.1", Section: "1.8", Title: "Compatibility with OAuth 2.0", Notes: "Compatibility guidance is exercised through the specific behavioral sections such as 10.2."},
	{Spec: "OAuth 2.1", Section: "1.9", Title: "Notational Conventions", Notes: "Notation guidance is not a direct runtime integration-test target."},
	{Spec: "OAuth 2.1", Section: "2", Title: "Client Registration", Notes: "Concrete client registration and redirect handling requirements are covered by the applicable subsections below."},
	{Spec: "OAuth 2.1", Section: "2.1", Title: "Client Types", Applicable: true, Run: testOAuth21ClientTypes},
	{Spec: "OAuth 2.1", Section: "2.2", Title: "Client Identifier", Applicable: true, Run: testOAuth21ClientIdentifier},
	{Spec: "OAuth 2.1", Section: "2.3", Title: "Client Redirection Endpoint", Notes: "Concrete redirect protections are covered by the narrower sections on CSRF, mix-up, invalid endpoints, and native-app loopback handling instead of a standalone umbrella test."},
	{Spec: "OAuth 2.1", Section: "2.3.1", Title: "Registration Requirements", Notes: "Operator-configured client registration validates redirect URI shape at startup, while exact-match and loopback-port runtime behavior are covered by 2.3.5 and 8.4.2 rather than a single broad test here."},
	{Spec: "OAuth 2.1", Section: "2.3.2", Title: "Multiple Redirect URIs", Notes: "OAuth 2.1 makes redirect_uri optional when only one redirect URI is registered, but this provider intentionally requires redirect_uri because it only supports OpenID Connect authorization requests, where OIDC Core 3.1.2.1 requires it; it also does not support multiple registered redirect URIs. Native loopback redirect variation is covered separately under 8.4.2."},
	{Spec: "OAuth 2.1", Section: "2.3.3", Title: "Preventing CSRF Attacks", Applicable: true, Notes: "The provider-side suite focuses on state round-tripping and PKCE enforcement; the client-side choice among state, nonce, and PKCE remains outside this black-box provider surface.", Run: testOAuth21PreventingCSRFAttacks},
	{Spec: "OAuth 2.1", Section: "2.3.4", Title: "Preventing Mix-Up Attacks", Applicable: true, Run: testOAuth21PreventingMixUpAttacks},
	{Spec: "OAuth 2.1", Section: "2.3.5", Title: "Invalid Endpoint", Applicable: true, Run: testOAuth21InvalidEndpoint},
	{Spec: "OAuth 2.1", Section: "2.3.6", Title: "Endpoint Content", Notes: "Redirect endpoint content is RP-side behavior and not implemented by this provider."},
	{Spec: "OAuth 2.1", Section: "2.4", Title: "Client Authentication", Applicable: true, Run: testClientAuthentication},
	{Spec: "OAuth 2.1", Section: "2.4.1", Title: "Client Secret", Applicable: true, Run: testTokenRequest},
	{Spec: "OAuth 2.1", Section: "2.4.2", Title: "Other Authentication Methods", Notes: "The product supports client_secret_basic, client_secret_post, and public clients without other authentication methods."},
	{Spec: "OAuth 2.1", Section: "2.5", Title: "Unregistered Clients", Notes: "Use of unregistered clients is beyond the scope of OAuth 2.1; unknown-client failures are still exercised under client-identification and error-handling coverage."},
	{Spec: "OAuth 2.1", Section: "3", Title: "Protocol Endpoints", Notes: "Authorization, token, and protected-resource behavior is covered by the applicable subsections below."},
	{Spec: "OAuth 2.1", Section: "3.1", Title: "Authorization Endpoint", Applicable: true, Run: testOAuth21AuthorizationEndpoint},
	{Spec: "OAuth 2.1", Section: "3.2", Title: "Token Endpoint", Notes: "Concrete token-endpoint behavior is covered by the narrower sections 3.2.1 through 3.2.4 instead of a standalone umbrella test."},
	{Spec: "OAuth 2.1", Section: "3.2.1", Title: "Client Authentication", Applicable: true, Run: testClientAuthentication},
	{Spec: "OAuth 2.1", Section: "3.2.2", Title: "Token Endpoint Request", Applicable: true, Run: testTokenRequest},
	{Spec: "OAuth 2.1", Section: "3.2.3", Title: "Token Endpoint Response", Applicable: true, Notes: "This OAuth-focused entry covers access-token response fields; OIDC-specific ID Token assertions live under OIDC Core.", Run: testOAuth21TokenEndpointResponse},
	{Spec: "OAuth 2.1", Section: "3.2.4", Title: "Token Endpoint Error Response", Applicable: true, Run: testTokenErrorResponse},
	{Spec: "OAuth 2.1", Section: "4", Title: "Grant Types", Notes: "The authorization code grant is covered by the applicable subsections below; other grants are documented separately as not implemented."},
	{Spec: "OAuth 2.1", Section: "4.1", Title: "Authorization Code Grant", Applicable: true, Run: testOAuth21AuthorizationCodeGrant},
	{Spec: "OAuth 2.1", Section: "4.1.1", Title: "Authorization Request", Notes: "This provider intentionally enforces a stricter S256-only PKCE policy and does not implement the draft's optional/default plain behavior; that stricter posture is exercised under section 7.5.1."},
	{Spec: "OAuth 2.1", Section: "4.1.2", Title: "Authorization Response", Applicable: true, Notes: "Covers both successful and error redirect responses; end-user authentication and consent interactions are covered by the OIDC Core flow sections.", Run: testOAuth21AuthorizationResponse},
	{Spec: "OAuth 2.1", Section: "4.1.3", Title: "Token Endpoint Extension", Applicable: true, Run: testOAuth21TokenEndpointExtension},
	{Spec: "OAuth 2.1", Section: "4.2", Title: "Client Credentials Grant", Notes: "The client credentials grant is not implemented."},
	{Spec: "OAuth 2.1", Section: "4.2.1", Title: "Token Endpoint Extension", Notes: "The client credentials grant is not implemented."},
	{Spec: "OAuth 2.1", Section: "4.3", Title: "Refresh Token Grant", Applicable: true, Run: testOAuth21RefreshTokenGrant},
	{Spec: "OAuth 2.1", Section: "4.3.1", Title: "Token Endpoint Extension", Applicable: true, Run: testOAuth21RefreshTokenRequest},
	{Spec: "OAuth 2.1", Section: "4.3.2", Title: "Refresh Token Response", Applicable: true, Run: testOAuth21RefreshTokenResponse},
	{Spec: "OAuth 2.1", Section: "4.3.3", Title: "Refresh Token Recommendations", Applicable: true, Run: testOAuth21RefreshTokenRecommendations},
	{Spec: "OAuth 2.1", Section: "4.4", Title: "Extension Grants", Notes: "Extension grants are not implemented."},
	{Spec: "OAuth 2.1", Section: "5", Title: "Resource Requests", Notes: "Protected-resource access requirements are covered by the applicable subsections below."},
	{Spec: "OAuth 2.1", Section: "5.1", Title: "Bearer Token Requests", Applicable: true, Notes: "This entry focuses on the one-method-only rule and URI-query prohibition; the concrete header and form methods are covered by 5.1.1 and 5.1.2.", Run: testOAuth21BearerTokenRequests},
	{Spec: "OAuth 2.1", Section: "5.1.1", Title: "Authorization Request Header Field", Applicable: true, Run: testOAuth21BearerAuthorizationHeaderField},
	{Spec: "OAuth 2.1", Section: "5.1.2", Title: "Form-Encoded Content Parameter", Applicable: true, Run: testOAuth21FormEncodedContentParameter},
	{Spec: "OAuth 2.1", Section: "5.2", Title: "Access Token Validation", Applicable: true, Run: testOAuth21AccessTokenValidation},
	{Spec: "OAuth 2.1", Section: "5.3", Title: "Error Response", Notes: "Concrete challenge formatting and bearer error codes are covered by sections 5.3.1 and 5.3.2 instead of a standalone umbrella test."},
	{Spec: "OAuth 2.1", Section: "5.3.1", Title: "The WWW-Authenticate Response Header Field", Applicable: true, Run: testOAuth21WWWAuthenticateResponseHeaderField},
	{Spec: "OAuth 2.1", Section: "5.3.2", Title: "Error Codes", Applicable: true, Notes: "The single UserInfo resource exercised by this suite surfaces invalid_request and invalid_token; it does not expose a distinct higher-privilege resource variant that would trigger insufficient_scope.", Run: testOAuth21ErrorCodes},
	{Spec: "OAuth 2.1", Section: "6", Title: "Extensibility", Notes: "Extensibility sections are not direct runtime integration-test targets for this product."},
	{Spec: "OAuth 2.1", Section: "6.1", Title: "Defining Access Token Types", Notes: "Access-token type extensibility and registry mechanics are not direct runtime integration-test targets."},
	{Spec: "OAuth 2.1", Section: "6.1.1", Title: "Registered Access Token Types", Notes: "IANA registry contents are not runtime integration-test targets."},
	{Spec: "OAuth 2.1", Section: "6.1.2", Title: "Vendor-Specific Access Token Types", Notes: "Vendor-specific access-token type definitions are not implemented or exposed as a distinct runtime surface."},
	{Spec: "OAuth 2.1", Section: "6.2", Title: "Defining New Endpoint Parameters", Notes: "Extension parameter definitions are specification-extensibility text, not a provider runtime target."},
	{Spec: "OAuth 2.1", Section: "6.3", Title: "Defining New Authorization Grant Types", Notes: "Extension grants are not implemented."},
	{Spec: "OAuth 2.1", Section: "6.4", Title: "Defining New Authorization Endpoint Response Types", Notes: "Extension response types are not implemented."},
	{Spec: "OAuth 2.1", Section: "6.5", Title: "Defining Additional Error Codes", Notes: "Extension error-code registration is not a direct runtime integration-test target."},
	{Spec: "OAuth 2.1", Section: "7", Title: "Security Considerations", Notes: "Concrete security requirements are covered by the applicable subsections below; transport security is documented separately as out of scope."},
	{Spec: "OAuth 2.1", Section: "7.1", Title: "Access Token Security Considerations", Notes: "Concrete bearer-token handling requirements are covered by the applicable subsections below; client-side TLS obligations are documented separately as out of scope."},
	{Spec: "OAuth 2.1", Section: "7.1.1", Title: "Security Threats", Notes: "Threat taxonomy is informational; concrete mitigations are covered by later subsections."},
	{Spec: "OAuth 2.1", Section: "7.1.2", Title: "Threat Mitigation", Notes: "The specific mitigations relevant to this product are covered by the concrete subsections below."},
	{Spec: "OAuth 2.1", Section: "7.1.3", Title: "Summary of Recommendations", Applicable: true, Notes: "Covers the implemented bearer-token handling recommendations; client-side TLS recommendations remain out of scope in the loopback harness.", Run: testOAuth21SummaryOfRecommendations},
	{Spec: "OAuth 2.1", Section: "7.1.4", Title: "Access Token Privilege Restriction", Notes: "This single-resource provider does not expose audience-restricted token issuance as a meaningful black-box surface; scope restriction is covered by access-token scope tests."},
	{Spec: "OAuth 2.1", Section: "7.2", Title: "Client Authentication", Notes: "This section is informational guidance about client trust levels rather than a discrete black-box provider behavior."},
	{Spec: "OAuth 2.1", Section: "7.3", Title: "Client Impersonation", Notes: "The provider requires explicit end-user authentication and consent for authorization requests; broader client-impersonation risk management is not a separate black-box integration-test surface."},
	{Spec: "OAuth 2.1", Section: "7.3.1", Title: "Impersonation of Native Apps", Notes: "Native clients are treated as public clients and are not auto-approved; platform identity proofs such as claimed https redirects are not implemented."},
	{Spec: "OAuth 2.1", Section: "7.3.2", Title: "Access Token Privilege Restriction", Notes: "This single-resource provider does not expose audience-restricted token issuance as a meaningful black-box surface."},
	{Spec: "OAuth 2.1", Section: "7.4", Title: "Client Impersonating Resource Owner", Notes: "Client IDs are server-configured and cannot be chosen by clients; the client credentials grant is not implemented."},
	{Spec: "OAuth 2.1", Section: "7.5", Title: "Authorization Code Security Considerations", Notes: "Concrete authorization-code protections are covered by the narrower sections 7.5.1, 7.5.2, and 7.5.3 instead of a standalone umbrella test."},
	{Spec: "OAuth 2.1", Section: "7.5.1", Title: "Authorization Code Injection", Applicable: true, Notes: "The suite verifies strict PKCE enforcement, including confidential requests that also supply an OIDC nonce; this provider intentionally does not rely on draft-specific latitude to relax PKCE.", Run: testOAuth21AuthorizationCodeInjectionCountermeasures},
	{Spec: "OAuth 2.1", Section: "7.5.2", Title: "Reuse of Authorization Codes", Applicable: true, Run: testOAuth21ReuseOfAuthorizationCodes},
	{Spec: "OAuth 2.1", Section: "7.5.3", Title: "HTTP 307 Redirect", Applicable: true, Run: testHTTP307Redirects},
	{Spec: "OAuth 2.1", Section: "7.6", Title: "Ensuring Endpoint Authenticity", Notes: "Endpoint authenticity depends on TLS; HTTPS/TLS enforcement is explicitly out of scope in the loopback harness."},
	{Spec: "OAuth 2.1", Section: "7.7", Title: "Credentials-Guessing Attacks", Notes: "Credential entropy requirements are not directly measurable through black-box integration tests."},
	{Spec: "OAuth 2.1", Section: "7.8", Title: "Phishing Attacks", Notes: "Phishing-resistance guidance is informational and not directly testable here."},
	{Spec: "OAuth 2.1", Section: "7.9", Title: "Cross-Site Request Forgery", Applicable: true, Run: testOAuth21PreventingCSRFAttacks},
	{Spec: "OAuth 2.1", Section: "7.10", Title: "Clickjacking", Applicable: true, Run: testOAuth21Clickjacking},
	{Spec: "OAuth 2.1", Section: "7.11", Title: "Injection and Input Validation", Applicable: true, Run: testOAuth21InjectionAndInputValidation},
	{Spec: "OAuth 2.1", Section: "7.12", Title: "Open Redirection", Notes: "Invalid redirect_uri rejection is covered under 2.3.5. The registered-redirect phishing scenario in 7.12.2 assumes attacker-controlled client registration, which this product does not implement because clients are operator-configured."},
	{Spec: "OAuth 2.1", Section: "7.12.1", Title: "Client as Open Redirector", Notes: "Client redirect endpoints are RP-side behavior and not implemented by this provider."},
	{Spec: "OAuth 2.1", Section: "7.12.2", Title: "Authorization Server as Open Redirector", Notes: "The registered-redirect phishing scenario assumes attacker-controlled client registration; this product uses operator-configured clients and does not implement dynamic or self-service client registration."},
	{Spec: "OAuth 2.1", Section: "7.13", Title: "Transport Security", Notes: "HTTPS enforcement is explicitly out of scope for this task."},
	{Spec: "OAuth 2.1", Section: "7.14", Title: "Authorization Server Mix-Up Mitigation", Applicable: true, Run: testOAuth21MixUpDefenseViaIssuerIdentification},
	{Spec: "OAuth 2.1", Section: "7.14.1", Title: "Mix-Up Defense via Issuer Identification", Applicable: true, Run: testOAuth21MixUpDefenseViaIssuerIdentification},
	{Spec: "OAuth 2.1", Section: "7.14.2", Title: "Mix-Up Defense via Distinct Redirect URIs", Notes: "Issuer identification is the mix-up defense implemented by this product."},
	{Spec: "OAuth 2.1", Section: "8", Title: "Native Applications", Notes: "Concrete native-app behavior is covered by sections 8.1, 8.1.1, 8.4.2, and 8.5.4 rather than a standalone umbrella test."},
	{Spec: "OAuth 2.1", Section: "8.1", Title: "Client Authentication of Native Apps", Applicable: true, Run: testOAuth21ClientAuthenticationOfNativeApps},
	{Spec: "OAuth 2.1", Section: "8.1.1", Title: "Registration of Native App Clients", Applicable: true, Run: testOAuth21RegistrationOfNativeAppClients},
	{Spec: "OAuth 2.1", Section: "8.1.2", Title: "Native App Attestation", Notes: "Native app attestation is not implemented."},
	{Spec: "OAuth 2.1", Section: "8.2", Title: "Using Inter-App URI Communication for OAuth in Native Applications", Notes: "The product only supports loopback redirects for native clients."},
	{Spec: "OAuth 2.1", Section: "8.3", Title: "Initiating the Authorization Request from a Native App", Notes: "User-agent launch behavior is client-side and outside this provider-focused suite."},
	{Spec: "OAuth 2.1", Section: "8.4", Title: "Receiving the Authorization Response in a Native App", Notes: "Only loopback interface redirection is implemented and covered by the applicable subsection below."},
	{Spec: "OAuth 2.1", Section: "8.4.1", Title: "Claimed \"https\" Scheme URI Redirection", Notes: "The product only supports loopback redirects for native clients."},
	{Spec: "OAuth 2.1", Section: "8.4.2", Title: "Loopback Interface Redirection", Applicable: true, Run: testOAuth21LoopbackInterfaceRedirection},
	{Spec: "OAuth 2.1", Section: "8.4.3", Title: "Private-Use URI Scheme Redirection", Notes: "The product only supports loopback redirects for native clients."},
	{Spec: "OAuth 2.1", Section: "8.5", Title: "Security Considerations in Native Apps", Notes: "Client-side user-agent considerations are out of scope; the provider-side loopback considerations are covered by the applicable subsection below."},
	{Spec: "OAuth 2.1", Section: "8.5.1", Title: "Embedded User Agents in Native Apps", Notes: "User-agent selection is client-side and outside this provider-focused suite."},
	{Spec: "OAuth 2.1", Section: "8.5.2", Title: "Fake External User-Agents in Native Apps", Notes: "User-agent selection is client-side and outside this provider-focused suite."},
	{Spec: "OAuth 2.1", Section: "8.5.3", Title: "Malicious External User-Agents in Native Apps", Notes: "User-agent selection is client-side and outside this provider-focused suite."},
	{Spec: "OAuth 2.1", Section: "8.5.4", Title: "Loopback Redirect Considerations in Native Apps", Applicable: true, Run: testOAuth21LoopbackRedirectConsiderations},
	{Spec: "OAuth 2.1", Section: "9", Title: "Browser-Based Apps", Notes: "Browser-based applications are explicitly out of scope for this backend-only product."},
	{Spec: "OAuth 2.1", Section: "10", Title: "Differences from OAuth 2.0", Notes: "Concrete behavioral differences from OAuth 2.0 are covered by the applicable subsections below."},
	{Spec: "OAuth 2.1", Section: "10.1", Title: "Removal of the OAuth 2.0 Implicit grant", Applicable: true, Run: testOAuth21RemovalOfImplicitGrant},
	{Spec: "OAuth 2.1", Section: "10.2", Title: "Redirect URI Parameter in Token Request", Applicable: true, Run: testOAuth21RedirectURIParameterInTokenRequest},
	{Spec: "OAuth 2.1", Section: "11", Title: "IANA Considerations", Notes: "IANA registration text is not a runtime integration-test target."},
	{Spec: "OAuth 2.1", Section: "12", Title: "References", Notes: "Reference sections are not runtime integration-test targets."},
	{Spec: "OAuth 2.1", Section: "12.1", Title: "Normative References", Notes: "Reference sections are not runtime integration-test targets."},
	{Spec: "OAuth 2.1", Section: "12.2", Title: "Informative References", Notes: "Reference sections are not runtime integration-test targets."},
}

func TestOAuth21Sections(t *testing.T) {
	runSpecSections(t, oauth21Sections)
}
